import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import type { ColumnInfo, RlsTable } from "./model.js";
import { parseProject } from "./parse-project.js";
import { isAppliedSqlFile, parseSqlForRls, sqlSchemaFor } from "./rls.js";
import { splitSqlStatements } from "./sql-lexer.js";

function parse(...files: string[]) {
  const tables = new Map<string, RlsTable>();
  files.forEach((sql, i) => {
    parseSqlForRls(`m${i}.sql`, sql, tables);
  });
  return { tables, ...sqlSchemaFor(tables) };
}

function cols(tables: Map<string, RlsTable>, table: string): Record<string, ColumnInfo> {
  return Object.fromEntries((tables.get(table)?.columnInfo ?? []).map((c) => [c.name, c]));
}

const FIXTURES = fileURLToPath(new URL("../../../evals/fixtures/", import.meta.url));

function tempProject(files: Record<string, string>): string {
  const dir = mkdtempSync(join(tmpdir(), "auditai-sql-"));
  for (const [rel, text] of Object.entries(files)) {
    mkdirSync(dirname(join(dir, rel)), { recursive: true });
    writeFileSync(join(dir, rel), text);
  }
  return dir;
}

describe("splitSqlStatements", () => {
  it("does not split inside strings, quoted identifiers, dollar bodies or comments", () => {
    const sql = [
      "insert into t (a) values ('x;y'); -- c;omment",
      'create table "we;ird" (id int);',
      "/* block; /* nested; */ still */ select E'it\\'s;';",
      "create function f() returns int as $function$ select 1; $$ not the end $$; $function$ language sql;",
      "select 2",
    ].join("\n");
    const stmts = splitSqlStatements(sql);
    expect(stmts.map((s) => s.tokens[0]?.value)).toEqual([
      "insert",
      "create",
      "select",
      "create",
      "select",
    ]);
    expect(stmts.map((s) => s.line)).toEqual([1, 2, 3, 4, 5]);
    expect(stmts[2]?.tokens[1]?.value).toBe("it's;");
    expect(stmts[3]?.tokens.find((t) => t.kind === "string")?.value).toBe(
      " select 1; $$ not the end $$; ",
    );
  });

  it("survives unterminated strings, bodies and comments", () => {
    for (const bad of ["select 'abc", 'select "abc', "select $$ abc", "select /* abc", "$", "'"]) {
      expect(() => splitSqlStatements(bad)).not.toThrow();
    }
  });
});

describe("CREATE TABLE column knowledge", () => {
  it("normalizes types and keeps modifiers and array dimensions", () => {
    const { tables } = parse(`
      create table public.t (
        a uuid, b text, c varchar(80), d character varying(255), e int, f int4, g integer,
        h bigint, i int8, j numeric(10, 2), k decimal, l boolean, m bool, n timestamptz,
        o timestamp with time zone, p timestamp(3), q timestamp without time zone, r date,
        s jsonb, u json, v text[], w integer array, x varchar(20)[], y double precision,
        z public.status, aa "Status", ab "public"."status"[], ac interval day to second,
        ad smallint, ae real, af time with time zone, ag int[][]
      );`);
    const types = (tables.get("t")?.columnInfo ?? []).map((c) => [c.name, c.type]);
    expect(Object.fromEntries(types)).toEqual({
      a: "uuid",
      b: "text",
      c: "varchar(80)",
      d: "varchar(255)",
      e: "integer",
      f: "integer",
      g: "integer",
      h: "bigint",
      i: "bigint",
      j: "numeric(10,2)",
      k: "numeric",
      l: "boolean",
      m: "boolean",
      n: "timestamptz",
      o: "timestamptz",
      p: "timestamp(3)",
      q: "timestamp",
      r: "date",
      s: "jsonb",
      u: "json",
      v: "text[]",
      w: "integer[]",
      x: "varchar(20)[]",
      y: "double precision",
      z: "status",
      aa: "status",
      ab: "status[]",
      ac: "interval",
      ad: "smallint",
      ae: "real",
      af: "timetz",
      ag: "integer[][]",
    });
  });

  it("reads nullability and defaults (NOT NULL, PRIMARY KEY, serial, identity, generated)", () => {
    const { tables } = parse(`
      create table t (
        id bigserial primary key,
        n serial,
        idn bigint generated by default as identity,
        ida int generated always as identity (start with 10),
        g text generated always as (upper(name)) stored,
        name text not null,
        d1 timestamptz not null default now(),
        d2 text default null,
        d3 text default 'open'::text not null,
        explicit_null text null,
        owner_id uuid references profiles on delete set null,
        c text check (c <> '') collate "C"
      );`);
    const c = cols(tables, "t");
    const flags = (name: string) => [c[name]?.type, c[name]?.nullable, c[name]?.hasDefault];
    expect(flags("id")).toEqual(["bigint", false, true]);
    expect(flags("n")).toEqual(["integer", false, true]);
    expect(flags("idn")).toEqual(["bigint", false, true]);
    expect(flags("ida")).toEqual(["integer", false, true]);
    expect(flags("g")).toEqual(["text", true, true]);
    expect(flags("name")).toEqual(["text", false, false]);
    expect(flags("d1")).toEqual(["timestamptz", false, true]);
    expect(flags("d2")).toEqual(["text", true, false]);
    expect(flags("d3")).toEqual(["text", false, true]);
    expect(flags("explicit_null")).toEqual(["text", true, false]);
    expect(flags("owner_id")).toEqual(["uuid", true, false]);
    expect(flags("c")).toEqual(["text", true, false]);
    expect(tables.get("t")?.columns).toEqual(
      (tables.get("t")?.columnInfo ?? []).map((x) => x.name),
    );
  });

  it("reads inline and table-level foreign keys, auth.users and composite keys", () => {
    const { tables } = parse(`
      create table public.tenants (id uuid primary key);
      create table "public"."orgs" ("slug" text, "region" text, primary key ("slug", "region"));
      create table public.profiles (
        id uuid primary key references auth.users (id) on delete cascade,
        tenant_id uuid not null references public.tenants,
        "orgSlug" text, org_region text,
        parent_id uuid,
        constraint profiles_org_fk foreign key ("orgSlug", org_region) references "public"."orgs",
        foreign key (parent_id) references profiles (id)
      );
      create table node (parent uuid references node, id uuid primary key);`);
    const p = cols(tables, "profiles");
    expect(p.id?.references).toEqual({ table: "auth.users", column: "id" });
    expect(p.tenant_id?.references).toEqual({ table: "tenants", column: "id" });
    expect(p.orgslug?.references).toEqual({ table: "orgs", column: "slug" });
    expect(p.orgslug?.sqlName).toBe("orgSlug");
    expect(p.org_region?.references).toEqual({ table: "orgs", column: "region" });
    expect(p.parent_id?.references).toEqual({ table: "profiles", column: "id" });
    expect(cols(tables, "orgs").slug?.nullable).toBe(false);
    expect(cols(tables, "node").parent?.references).toEqual({ table: "node", column: "id" });
  });

  it("keys other schemas qualified and keeps exact names of quoted mixed-case tables", () => {
    const { tables } = parse(`
      create table private.secrets (id uuid primary key);
      create table "Invoice" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL);`);
    expect([...tables.keys()]).toEqual(["private.secrets", "invoice"]);
    expect(tables.get("invoice")?.sqlName).toBe("Invoice");
    expect(tables.get("invoice")?.columns).toEqual(["id", "tenantid"]);
    expect(cols(tables, "invoice").tenantid?.sqlName).toBe("tenantId");
    expect(cols(tables, "invoice").id?.sqlName).toBeUndefined();
  });

  it("treats CREATE TABLE IF NOT EXISTS on an existing table as a no-op and a re-create as a replacement", () => {
    const { tables } = parse(
      "create table a (id int, x text); create table if not exists a (id int, y text);",
      "drop table a; create table a (id int, z text);",
    );
    expect(tables.get("a")?.columns).toEqual(["id", "z"]);
  });
});

describe("ALTER TABLE, DROP TABLE and file order", () => {
  it("applies column changes in order", () => {
    const { tables } = parse(
      `create table public.t (id uuid primary key, a text, b text not null, c int default 1, d varchar(10));`,
      `alter table public.t add column if not exists e uuid references public.t (id);
       alter table t add f text not null default '', drop column a;
       alter table only "public"."t" alter column b drop not null, alter column c drop default;
       alter table t alter c set not null, alter column d set data type text;
       alter table t alter column e type uuid using e::uuid, alter column b set default 'x';
       alter table t rename column d to description;
       alter table if exists t add column if not exists f text;`,
    );
    const t = tables.get("t");
    expect(t?.columns).toEqual(["id", "b", "c", "description", "e", "f"]);
    const c = cols(tables, "t");
    expect([c.b?.nullable, c.b?.hasDefault]).toEqual([true, true]);
    expect([c.c?.nullable, c.c?.hasDefault]).toEqual([false, false]);
    expect(c.description?.type).toBe("text");
    expect(c.e?.references).toEqual({ table: "t", column: "id" });
    expect([c.f?.nullable, c.f?.hasDefault, c.f?.type]).toEqual([false, true, "text"]);
  });

  it("follows renames and drops into foreign keys", () => {
    const { tables } = parse(
      `create table tenants (id uuid primary key, code text unique);
       create table invoices (id uuid primary key, tenant_id uuid references tenants (id), tenant_code text);
       alter table invoices add constraint inv_code_fk foreign key (tenant_code) references tenants (code);`,
      `alter table tenants rename column id to tenant_uuid;
       alter table tenants rename to organizations;`,
    );
    expect([...tables.keys()]).toEqual(["invoices", "organizations"]);
    expect(cols(tables, "invoices").tenant_id?.references).toEqual({
      table: "organizations",
      column: "tenant_uuid",
    });
    const dropped = parse(
      `create table tenants (id uuid primary key, code text);
       create table invoices (id uuid, tenant_id uuid references tenants (id), tenant_code text,
         constraint inv_code_fk foreign key (tenant_code) references tenants (code));
       alter table invoices drop constraint if exists inv_code_fk;
       alter table tenants drop column id cascade;`,
    );
    expect(cols(dropped.tables, "invoices").tenant_id?.references).toBeNull();
    expect(cols(dropped.tables, "invoices").tenant_code?.references).toBeNull();
    const gone = parse(
      "create table a (id int primary key); create table b (a_id int references a); drop table if exists a cascade;",
    );
    expect([...gone.tables.keys()]).toEqual(["b"]);
    expect(cols(gone.tables, "b").a_id?.references).toBeNull();
  });

  it("drops a default-named inline foreign key and reads PRIMARY KEY USING INDEX", () => {
    const { tables } = parse(`
      create table "public"."todos" ("id" bigint not null, "user_id" uuid references auth.users);
      CREATE UNIQUE INDEX todos_pkey ON public.todos USING btree (id);
      alter table "public"."todos" add constraint "todos_pkey" PRIMARY KEY using index "todos_pkey";
      alter table "public"."todos" drop constraint "todos_user_id_fkey";`);
    expect(cols(tables, "todos").user_id?.references).toBeNull();
    expect(cols(tables, "todos").id?.nullable).toBe(false);
  });

  it("ignores column changes for tables the migrations never create", () => {
    const { tables } = parse(
      "alter table ghost add column x int; alter table ghost2 enable row level security;",
    );
    expect([...tables.keys()]).toEqual(["ghost2"]);
    expect(tables.get("ghost2")?.columnInfo).toEqual([]);
  });
});

describe("enums", () => {
  it("reads CREATE TYPE ... AS ENUM and later ALTER TYPE statements", () => {
    const { enums, tables } = parse(
      `create type public.invoice_status as enum ('draft', 'open');
       CREATE TYPE "public"."Plan" AS ENUM('FREE', 'PRO');
       create type mood as enum ('sad');
       create type pair as (a int, b int);
       create table invoices (status invoice_status not null default 'draft', plan "Plan");`,
      `alter type invoice_status add value 'paid';
       alter type invoice_status add value if not exists 'open';
       alter type invoice_status add value 'void' before 'open';
       alter type invoice_status add value 'refunded' after 'paid';
       alter type "Plan" rename value 'PRO' to 'TEAM';
       alter type "Plan" rename to tier;
       drop type if exists mood;`,
    );
    expect(enums).toEqual({
      invoice_status: ["draft", "void", "open", "paid", "refunded"],
      tier: ["FREE", "TEAM"],
    });
    expect(cols(tables, "invoices").plan?.type).toBe("tier");
    expect(cols(tables, "invoices").status?.type).toBe("invoice_status");
  });

  it("reads enums and foreign keys wrapped in DO blocks (older drizzle-kit)", () => {
    const { enums, tables } = parse(`
      DO $$ BEGIN
       CREATE TYPE "public"."role" AS ENUM('owner', 'member');
      EXCEPTION
       WHEN duplicate_object THEN null;
      END $$;
      --> statement-breakpoint
      CREATE TABLE IF NOT EXISTS "members" ("id" uuid PRIMARY KEY NOT NULL, "team_id" uuid NOT NULL, "role" "role" DEFAULT 'member' NOT NULL);
      --> statement-breakpoint
      CREATE TABLE IF NOT EXISTS "teams" ("id" uuid PRIMARY KEY NOT NULL);
      --> statement-breakpoint
      DO $$ BEGIN
       ALTER TABLE "members" ADD CONSTRAINT "members_team_id_teams_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE cascade ON UPDATE no action;
      EXCEPTION
       WHEN duplicate_object THEN null;
      END $$;
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'kind') THEN
          CREATE TYPE kind AS ENUM ('a', 'b');
        END IF;
        ALTER TABLE members ENABLE ROW LEVEL SECURITY;
      END $$;`);
    expect(enums).toEqual({ role: ["owner", "member"], kind: ["a", "b"] });
    expect(cols(tables, "members").team_id?.references).toEqual({ table: "teams", column: "id" });
    expect(cols(tables, "members").role).toMatchObject({ type: "role", hasDefault: true });
    expect(tables.get("members")?.rlsEnabled).toBe(false);
  });
});

describe("DO blocks that loop over a literal list of tables (DeskcommCRM)", () => {
  const TABLES = `
    create table public.job_queue (id uuid primary key, organization_id uuid);
    create table public.send_ledger (id uuid primary key, organization_id uuid);
    create table public.metrics (id uuid primary key, organization_id uuid);`;

  it("unrolls foreach ... in array array[...] with execute format(%I, %s)", () => {
    const { tables, warnings } = parse(`${TABLES}
      do $$
      declare
        t text;
      begin
        foreach t in array array['job_queue', 'send_ledger'] loop
          execute format('alter table public.%I enable row level security', t);
          execute format('drop policy if exists tenant_isolation_%s_all on public.%I', t, t);
          execute format(
            'create policy tenant_isolation_%s_all on public.%I for all
               using (organization_id in (select * from public.fn_user_org_ids()))
               with check (organization_id in (select * from public.fn_user_org_ids()))',
            t, t
          );
          execute format('revoke all on public.%I from anon', t);
        end loop;
      end
      $$;`);
    expect(tables.get("job_queue")?.rlsEnabled).toBe(true);
    expect(tables.get("send_ledger")?.rlsEnabled).toBe(true);
    expect(tables.get("metrics")?.rlsEnabled).toBe(false);
    const policy = tables.get("send_ledger")?.policyDetails[0];
    expect(policy).toMatchObject({
      name: "tenant_isolation_send_ledger_all",
      command: "all",
      using: "organization_id in (select * from public.fn_user_org_ids())",
    });
    expect(policy?.location).toEqual({ file: "m0.sql", line: 5 });
    expect(warnings).toEqual([]);
  });

  it("applies drop policy, so a policy a later migration removes is gone", () => {
    const { tables } = parse(
      `create table public.suggestions (id uuid primary key, owner_id uuid);
alter table public.suggestions enable row level security;
create policy "Public insert suggestions" on suggestions for insert to anon with check (true);
create policy "owner reads" on public.suggestions for select using (owner_id = auth.uid());`,
      `drop policy if exists "Public insert suggestions" on suggestions;
drop policy if exists "never existed" on public.suggestions;
drop policy if exists "orphan" on public.no_such_table;`,
    );
    const t2 = tables.get("suggestions");
    expect(t2?.policies).toEqual(["owner reads"]);
    expect(t2?.policyDetails.map((p) => p.name)).toEqual(["owner reads"]);
    // A drop on a table no migration created must not invent the table.
    expect(tables.has("no_such_table")).toBe(false);
  });

  it("reads roles from the TO clause, quoted or bare, and never from the predicate", () => {
    const { tables } =
      parse(`create table public.notes (id uuid primary key, owner_id uuid, "to" text);
alter table public.notes enable row level security;
create policy "quoted" on "public"."notes" for delete to "authenticated" using (true);
create policy "two" on public.notes for update to authenticated, "service_role" using (true);
create policy "none" on public.notes for insert with check (true);
create policy "column named to" on public.notes for select using ("to" = 'x');`);
    const byName = Object.fromEntries(
      (tables.get("notes")?.policyDetails ?? []).map((p) => [p.name, p]),
    );
    expect(byName.quoted?.roles).toEqual(["authenticated"]);
    expect(byName.two?.roles).toEqual(["authenticated", "service_role"]);
    // No TO clause means PUBLIC in Postgres; an empty list is how the model spells that.
    expect(byName.none?.roles).toEqual([]);
    expect(byName["column named to"]?.roles).toEqual([]);
  });

  it("reads select unnest(array[...]), (values (...)) and declared lists, %L and %%, and plain execute strings", () => {
    const { tables, warnings } = parse(`${TABLES}
      do $$ declare t text; r record; v_tables text[] := array['job_queue']; begin
        for t in select unnest(array['job_queue']) loop
          execute format('alter table %I disable row level security', t);
        end loop;
        foreach t in array v_tables loop
          execute format('alter table %I enable row level security', t);
        end loop;
        for r in (values ('send_ledger'), ('metrics')) loop
          execute format('alter table public.%I enable row level security', r.column1);
          execute format('create policy %I on public.%I for select using (auth.uid() is not null and true = %L)', 'read ' || 'all', r.column1, 'true');
        end loop;
        execute 'alter table public.metrics disable row level security';
      end $$;`);
    expect(tables.get("job_queue")?.rlsEnabled).toBe(true);
    expect(tables.get("send_ledger")?.rlsEnabled).toBe(true);
    // The plain EXECUTE after the loop runs last and wins.
    expect(tables.get("metrics")?.rlsEnabled).toBe(false);
    expect(tables.get("send_ledger")?.policies).toEqual([]);
    // `'read ' || 'all'` is an expression, so that EXECUTE is dynamic: one warning for the file.
    expect(warnings).toHaveLength(1);
    expect(warnings[0]).toContain("m0.sql");
  });

  it("does not follow loops over queries, conditional executes or nested loops, and warns once per file", () => {
    const { tables, sqlFunctions, warnings } = parse(`${TABLES}
      create function public.fn_secret() returns text language sql security definer as $$ select 'x' $$;
      do $$ declare f record; begin
        for f in select p.oid::regprocedure as sig from pg_proc p where p.prosecdef loop
          execute format('revoke execute on function %s from public, anon', f.sig);
        end loop;
      end $$;
      do $$ declare t text; begin
        foreach t in array array['job_queue'] loop
          if to_regclass('public.' || t) is not null then
            execute format('alter table public.%I enable row level security', t);
          end if;
        end loop;
        foreach t in array array['send_ledger'] loop
          foreach t in array array['metrics'] loop
            execute format('alter table public.%I enable row level security', t);
          end loop;
        end loop;
      end $$;`);
    expect(tables.get("job_queue")?.rlsEnabled).toBe(false);
    expect(tables.get("send_ledger")?.rlsEnabled).toBe(false);
    expect(tables.get("metrics")?.rlsEnabled).toBe(false);
    expect(sqlFunctions?.find((f) => f.name === "fn_secret")?.grantedTo).toContain("anon");
    expect(warnings).toHaveLength(1);
    expect(warnings[0]).toMatch(/^m0\.sql: a DO block runs dynamic SQL/);
  });

  it("keeps the drizzle-kit behaviour: a bare ALTER TABLE inside a DO block is not an RLS switch", () => {
    const { tables, warnings } = parse(`${TABLES}
      do $$ begin
        alter table public.job_queue enable row level security;
      exception when others then null;
      end $$;`);
    expect(tables.get("job_queue")?.rlsEnabled).toBe(false);
    expect(warnings).toEqual([]);
  });

  it("survives malformed loops", () => {
    for (const sql of [
      "do $$ begin foreach t in array array['a' loop execute format('alter table %I enable row level security', t); end loop; end $$;",
      "do $$ begin foreach in array array['a'] loop execute format('%I %I', t); end $$;",
      "do $$ begin for t in (values ('a'), ('b' loop execute format('alter table %I enable row level security', t); end loop; end $$;",
      "do $$ begin foreach t in array array['a'] loop execute format('%3$I', t); end loop; end $$;",
      "do $$ begin foreach t in array array['a'] loop execute format('%q', t); end loop; end $$;",
      "do $$ begin foreach t in array array['a'] loop execute format(); end loop; end $$;",
      "do $$ begin foreach t in array array['a'] loop execute; end loop; end $$;",
      "do $$ begin end loop; end loop; end $$;",
      "do $$ $$;",
      "do",
    ]) {
      expect(() => parse(sql)).not.toThrow();
    }
  });
});

describe("SQL functions", () => {
  it("reads SECURITY DEFINER, caller checks (also through helpers) and return types", () => {
    const { sqlFunctions } = parse(`
      create or replace function public.current_tenant_id() returns uuid language sql stable
        security definer set search_path = public
        as $$ select tenant_id from public.profiles where id = (select auth.uid()) $$;
      create function public.list_invoices() returns setof invoices language sql security definer
        as $$ select * from invoices where tenant_id = public.current_tenant_id() $$;
      create function public.leak(p_id uuid) returns jsonb language plpgsql security definer as $body$
      begin
        -- TODO: check auth.uid() here
        if auth.role() = 'authenticated' then
          return (select to_jsonb(i) from invoices i where i.id = p_id);
        end if;
        return null;
      end;
      $body$;
      create function claims() returns text language sql as 'select current_setting(''request.jwt.claims'', true)';
      create function jwt_team() returns uuid language sql return (auth.jwt() ->> 'team_id')::uuid;
      create function private.handle_new_user() returns trigger language plpgsql security definer
        as $$ begin insert into public.profiles (id) values (new.id); return new; end; $$;
      create function public.invoker_fn() returns int language sql security invoker as $$ select 1 $$;
      create function strictly() returns int returns null on null input language sql as $$ select 1 $$;`);
    const byName = Object.fromEntries((sqlFunctions ?? []).map((f) => [f.name, f]));
    expect(Object.keys(byName)).toEqual([
      "current_tenant_id",
      "list_invoices",
      "leak",
      "claims",
      "jwt_team",
      "private.handle_new_user",
      "invoker_fn",
      "strictly",
    ]);
    expect(byName.current_tenant_id).toMatchObject({
      securityDefiner: true,
      checksCaller: true,
      returns: "uuid",
      location: { file: "m0.sql", line: 2 },
    });
    expect(byName.list_invoices).toMatchObject({
      securityDefiner: true,
      checksCaller: true,
      returns: "setof invoices",
    });
    expect(byName.leak).toMatchObject({
      securityDefiner: true,
      checksCaller: false,
      returns: "jsonb",
    });
    expect(byName.claims?.checksCaller).toBe(true);
    expect(byName.jwt_team?.checksCaller).toBe(true);
    expect(byName["private.handle_new_user"]).toMatchObject({
      securityDefiner: true,
      checksCaller: false,
      returns: "trigger",
      grantedTo: [],
    });
    expect(byName.invoker_fn?.securityDefiner).toBe(false);
    expect(byName.strictly?.returns).toBe("integer");
  });

  it("applies GRANT/REVOKE in order on top of the Supabase defaults", () => {
    const { sqlFunctions } = parse(
      `create function a() returns int language sql as $$ select 1 $$;
       create function b() returns int language sql as $$ select 1 $$;
       create function c(x uuid) returns int language sql as $$ select 1 $$;
       create function d() returns int language sql as $$ select 1 $$;
       create function e() returns int language sql as $$ select 1 $$;
       revoke execute on function b() from anon;
       revoke all on function public.c(uuid) from public, anon;
       revoke execute on function d from public, anon, authenticated;
       grant execute on function d() to service_role;
       revoke all privileges on function e() from "public", anon, authenticated;
       grant execute on function e to public;`,
      `create or replace function c(x uuid) returns int language sql as $$ select 2 $$;
       drop function if exists a();
       create function a() returns int language sql as $$ select 3 $$;`,
    );
    const granted = Object.fromEntries((sqlFunctions ?? []).map((f) => [f.name, f.grantedTo]));
    expect(granted).toEqual({
      // PUBLIC still holds EXECUTE, so revoking anon alone does not lock anon out.
      b: ["anon", "authenticated"],
      // CREATE OR REPLACE keeps the privileges set before it.
      c: ["authenticated"],
      d: ["service_role"],
      e: ["anon", "authenticated", "public"],
      // Dropped and re-created: back to the defaults.
      a: ["anon", "authenticated"],
    });
  });

  it("honours ALTER DEFAULT PRIVILEGES and schema-wide grants", () => {
    const { sqlFunctions } = parse(`
      create function before_lockdown() returns int language sql as $$ select 1 $$;
      alter default privileges revoke execute on functions from public;
      alter default privileges in schema public revoke execute on functions from anon, authenticated;
      create function after_lockdown() returns int language sql as $$ select 1 $$;
      create function api() returns int language sql as $$ select 1 $$;
      grant execute on function api to authenticated;
      revoke execute on all functions in schema public from public, anon;
      alter function public.api() security definer;`);
    const byName = Object.fromEntries((sqlFunctions ?? []).map((f) => [f.name, f]));
    expect(byName.before_lockdown?.grantedTo).toEqual(["authenticated"]);
    expect(byName.after_lockdown?.grantedTo).toEqual([]);
    expect(byName.api).toMatchObject({ grantedTo: ["authenticated"], securityDefiner: true });
  });

  it("reports definition lines after multi-line bodies correctly", () => {
    const { sqlFunctions, tables } = parse(
      [
        "create function f()",
        "returns trigger as $$",
        "begin",
        "  return new;",
        "end;",
        "$$ language plpgsql;",
        "",
        'create policy "p" on public.t for select using (true);',
      ].join("\n"),
    );
    expect(sqlFunctions?.[0]?.location.line).toBe(1);
    expect(tables.get("t")?.policyDetails[0]?.location.line).toBe(8);
  });
});

describe("SQL function call chains", () => {
  it("propagates caller checks through several helpers, qualified or found by name", () => {
    const { sqlFunctions } = parse(`
      create function top_level() returns setof uuid language sql security definer
        as $$ select id from invoices where tenant_id in (select middle()) $$;
      create function middle() returns uuid language sql security definer set search_path = private
        as $$ select tenant_for(helper_user()) $$;
      create function private.tenant_for(u uuid) returns uuid language sql
        as $$ select tenant_id from profiles where id = u $$;
      create function private.helper_user() returns uuid language sql as $$ select auth.uid() $$;
      create function unrelated() returns int language sql as $$ select count(*) from invoices $$;`);
    const checks = Object.fromEntries((sqlFunctions ?? []).map((f) => [f.name, f.checksCaller]));
    expect(checks).toEqual({
      top_level: true,
      middle: true,
      "private.tenant_for": false,
      "private.helper_user": true,
      unrelated: false,
    });
  });
});

describe("storage", () => {
  it("reads buckets from storage.buckets and keys storage policies qualified", () => {
    const { storageBuckets, tables } = parse(
      `insert into storage.buckets (id, name, public) values ('avatars', 'avatars', true), ('docs', 'docs', false);
       insert into storage.buckets (id, name) values ('private', 'private') on conflict (id) do nothing;
       insert into storage.buckets (id, name, public) values ('avatars', 'avatars', false) on conflict do nothing;
       create policy "read avatars" on storage.objects for select using (bucket_id = 'avatars');
       create policy "list buckets" on "storage"."buckets" for select using (true);`,
      `update storage.buckets set public = true where id = 'docs';
       delete from storage.buckets where id in ('private');`,
    );
    expect(storageBuckets?.map((b) => [b.id, b.public])).toEqual([
      ["avatars", true],
      ["docs", true],
    ]);
    expect(storageBuckets?.[0]?.location).toEqual({ file: "m0.sql", line: 1 });
    expect([...tables.keys()]).toEqual(["storage.objects", "storage.buckets"]);
    expect(tables.get("storage.objects")?.policies).toEqual(["read avatars"]);
  });
});

describe("migration files that are never applied", () => {
  it("skips SQL nested inside supabase/migrations/<subdir> (open-scouts old_migrations)", () => {
    expect(isAppliedSqlFile("supabase/migrations/0001_init.sql")).toBe(true);
    expect(isAppliedSqlFile("../supabase/migrations/0001_init.sql")).toBe(true);
    expect(isAppliedSqlFile("prisma/migrations/0_init/migration.sql")).toBe(true);
    expect(isAppliedSqlFile("supabase/migrations/old_migrations/2025_x.sql")).toBe(false);
    const body =
      "returns trigger as $$\nbegin\n  new.updated_at = now();\n  return new;\nend;\n$$ language plpgsql;";
    const tablesSql = ["scouts", "scout_messages", "user_preferences"]
      .map((t) => `create table if not exists ${t} (id uuid primary key);`)
      .join("\n");
    const dir = tempProject({
      "supabase/migrations/00000000000000_schema.sql": `${tablesSql}
create or replace function touch() ${body}
create trigger t before update on user_preferences for each row execute function touch();
ALTER TABLE scouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE scout_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_preferences ENABLE ROW LEVEL SECURITY;
`,
      "supabase/migrations/old_migrations/20251113124500_create_user_preferences.sql":
        "ALTER TABLE user_preferences DISABLE ROW LEVEL SECURITY;\nALTER TABLE scouts DISABLE ROW LEVEL SECURITY;",
    });
    const m = parseProject(dir);
    expect(m.tables.map((t) => [t.table, t.rlsEnabled])).toEqual([
      ["scouts", true],
      ["scout_messages", true],
      ["user_preferences", true],
    ]);
  });
});

describe("fixtures", () => {
  it("001 (Supabase CLI): column types, keys, references and the tenant helper function", () => {
    const m = parseProject(join(FIXTURES, "001-cross-tenant-invoice-read/vulnerable"), {
      sqlDirs: ["../supabase"],
    });
    const invoices = m.tables.find((t) => t.table === "invoices");
    expect(invoices?.columns).toEqual([
      "id",
      "tenant_id",
      "owner_id",
      "customer_name",
      "amount_cents",
      "created_at",
    ]);
    expect(invoices?.columnInfo).toEqual([
      { name: "id", type: "uuid", nullable: false, hasDefault: true, references: null },
      {
        name: "tenant_id",
        type: "uuid",
        nullable: false,
        hasDefault: false,
        references: { table: "tenants", column: "id" },
      },
      {
        name: "owner_id",
        type: "uuid",
        nullable: false,
        hasDefault: false,
        references: { table: "profiles", column: "id" },
      },
      { name: "customer_name", type: "text", nullable: false, hasDefault: false, references: null },
      {
        name: "amount_cents",
        type: "integer",
        nullable: false,
        hasDefault: false,
        references: null,
      },
      {
        name: "created_at",
        type: "timestamptz",
        nullable: false,
        hasDefault: true,
        references: null,
      },
    ]);
    const profiles = m.tables.find((t) => t.table === "profiles");
    expect(profiles?.columnInfo?.[0]?.references).toEqual({ table: "auth.users", column: "id" });
    expect(m.enums).toEqual({});
    expect(m.storageBuckets).toEqual([]);
    expect(m.sqlFunctions).toEqual([
      {
        name: "current_tenant_id",
        securityDefiner: true,
        checksCaller: true,
        grantedTo: ["anon", "authenticated"],
        location: { file: "../supabase/migrations/0001_init.sql", line: 26 },
        returns: "uuid",
        // Argument types, so a GRANT or REVOKE the fixer writes names the right overload.
        args: "",
      },
    ]);
    const policy = m.tables.find((t) => t.table === "invoices")?.policyDetails[0];
    expect(policy?.location.line).toBe(44);
  });

  it("013 (Drizzle kit): quoted identifiers and ALTER TABLE ... ADD CONSTRAINT foreign keys", () => {
    const m = parseProject(join(FIXTURES, "013-drizzle-direct-db-invoice-read/vulnerable"));
    const byTable = Object.fromEntries(m.tables.map((t) => [t.table, t]));
    expect(Object.keys(byTable)).toEqual(["tenants", "profiles", "invoices"]);
    expect(byTable.invoices?.columnInfo).toEqual([
      { name: "id", type: "uuid", nullable: false, hasDefault: true, references: null },
      {
        name: "tenant_id",
        type: "uuid",
        nullable: false,
        hasDefault: false,
        references: { table: "tenants", column: "id" },
      },
      {
        name: "amount_cents",
        type: "integer",
        nullable: false,
        hasDefault: false,
        references: null,
      },
      { name: "status", type: "text", nullable: false, hasDefault: true, references: null },
    ]);
    expect(byTable.profiles?.columnInfo?.[1]?.references).toEqual({
      table: "tenants",
      column: "id",
    });
    expect(byTable.invoices?.rlsEnabled).toBe(true);
  });

  it("014 (Prisma migrate): table-level PRIMARY KEY constraints and foreign keys", () => {
    const m = parseProject(join(FIXTURES, "014-prisma-direct-db-invoice-read/vulnerable"));
    const invoices = m.tables.find((t) => t.table === "invoices");
    expect(invoices?.columns).toEqual(["id", "tenant_id", "amount_cents", "status"]);
    expect(invoices?.columnInfo).toEqual([
      { name: "id", type: "uuid", nullable: false, hasDefault: false, references: null },
      {
        name: "tenant_id",
        type: "uuid",
        nullable: false,
        hasDefault: false,
        references: { table: "tenants", column: "id" },
      },
      {
        name: "amount_cents",
        type: "integer",
        nullable: false,
        hasDefault: false,
        references: null,
      },
      { name: "status", type: "text", nullable: false, hasDefault: true, references: null },
    ]);
    const profiles = m.tables.find((t) => t.table === "profiles");
    expect(profiles?.columnInfo?.[1]?.references).toEqual({ table: "tenants", column: "id" });
  });

  it("Prisma default naming: PascalCase tables, camelCase columns, enums and precise types", () => {
    const { tables, enums } = parse(`
      -- CreateEnum
      CREATE TYPE "Status" AS ENUM ('OPEN', 'PAID');
      -- CreateTable
      CREATE TABLE "Invoice" (
          "id" TEXT NOT NULL,
          "tenantId" TEXT NOT NULL,
          "status" "Status" NOT NULL DEFAULT 'OPEN',
          "total" DECIMAL(65,30) NOT NULL,
          "tags" TEXT[],
          "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
          CONSTRAINT "Invoice_pkey" PRIMARY KEY ("id")
      );
      CREATE TABLE "Tenant" ("id" TEXT NOT NULL, CONSTRAINT "Tenant_pkey" PRIMARY KEY ("id"));
      -- AddForeignKey
      ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;`);
    expect(enums).toEqual({ status: ["OPEN", "PAID"] });
    expect(tables.get("invoice")?.sqlName).toBe("Invoice");
    expect(tables.get("invoice")?.columnInfo).toEqual([
      { name: "id", type: "text", nullable: false, hasDefault: false, references: null },
      {
        name: "tenantid",
        sqlName: "tenantId",
        type: "text",
        nullable: false,
        hasDefault: false,
        references: { table: "tenant", column: "id" },
      },
      { name: "status", type: "status", nullable: false, hasDefault: true, references: null },
      {
        name: "total",
        type: "numeric(65,30)",
        nullable: false,
        hasDefault: false,
        references: null,
      },
      { name: "tags", type: "text[]", nullable: true, hasDefault: false, references: null },
      {
        name: "createdat",
        sqlName: "createdAt",
        type: "timestamp(3)",
        nullable: false,
        hasDefault: true,
        references: null,
      },
    ]);
  });
});

describe("malformed SQL", () => {
  it("never throws and keeps what it can read", () => {
    const junk = [
      "create table",
      "create table t (",
      "create table t (id uuid primary key, tenant_id uuid references",
      "create table u (id int, , , name)",
      "alter table",
      "alter table t add column",
      "alter table t alter column",
      "alter table t rename",
      "alter table t drop constraint",
      "alter table t add constraint x foreign key (",
      "create type e as enum (",
      "alter type e add value",
      "alter type",
      "create function f(",
      "create function g() returns",
      "grant execute on function",
      "revoke all on all functions in schema",
      "alter default privileges in schema public grant",
      "insert into storage.buckets (id, public) values ('x', ",
      "update storage.buckets set",
      "delete from storage.buckets where id in (",
      "do $$ begin if then",
      "create policy",
      "create policy p on",
      "drop table if exists",
      "create unique index on",
      "))) ((( ;;; $$ '' \"\" -- /*",
    ];
    for (const sql of junk) {
      expect(() => parse(`${sql}`)).not.toThrow();
      expect(() => parse(`${sql};`)).not.toThrow();
    }
    const truncated = parse(
      "create table a (id uuid primary key, name text not null); create table b (id uuid, a_id uuid references a(",
    );
    expect(cols(truncated.tables, "a").name).toMatchObject({ type: "text", nullable: false });
    expect(truncated.tables.get("b")?.columns).toEqual(["id", "a_id"]);
  });

  it("stays linear on hostile sizes (long identifier runs, unbalanced groups)", () => {
    const run = "a".repeat(300_000);
    const started = Date.now();
    const { sqlFunctions, tables } = parse(
      `create function f() returns int language sql as $$ select ${run} $$;`,
      `create table t (id int, x text default ${run});`,
      `create policy p on t using (${"(".repeat(50_000)});`,
      `select ${"(".repeat(100_000)}`,
    );
    expect(Date.now() - started).toBeLessThan(4000);
    expect(sqlFunctions?.[0]?.checksCaller).toBe(false);
    expect(tables.get("t")?.columns).toEqual(["id", "x"]);
  });

  it("keeps a hostile enum name as a plain key", () => {
    const { enums } = parse(`create type "__proto__" as enum ('x');`);
    expect(Object.getPrototypeOf(enums)).toBe(Object.prototype);
    expect(Object.keys(enums)).toEqual(["__proto__"]);
  });
});

describe("function argument types (for GRANT and REVOKE)", () => {
  it("reads names, modes, defaults, arrays and qualified types", () => {
    const { sqlFunctions } =
      parse(`create function public.a() returns void language sql as $$ select 1 $$;
create function public.b(p_id uuid, count integer default 0) returns void language sql as $$ select 1 $$;
create function public.c(uuid, text[]) returns void language sql as $$ select 1 $$;
create function public.d(in p_from date, in p_to date, variadic tags text[]) returns void language sql as $$ select 1 $$;
create function public.e(p_id uuid, out found boolean) returns boolean language sql as $$ select true $$;
create function public.f(p_at timestamp with time zone, p_num numeric(10, 2)) returns void language sql as $$ select 1 $$;`);
    const byName = Object.fromEntries(sqlFunctions.map((f) => [f.name, f.args]));
    expect(byName.a).toBe("");
    expect(byName.b).toBe("uuid, integer");
    // A single word per parameter is the type, not a name.
    expect(byName.c).toBe("uuid, text[]");
    expect(byName.d).toBe("date, date, text[]");
    // OUT parameters are not part of the signature Postgres identifies a function by.
    expect(byName.e).toBe("uuid");
    expect(byName.f).toBe("timestamp with time zone, numeric(10, 2)");
  });
});
