import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { buildGraph } from "@auditai/graph";
import { parseProject } from "@auditai/parser";
import { describe, expect, it } from "vitest";
import { runRules } from "../rule.js";
import { userControlledTenantScope } from "./supabase-authorization.js";

/**
 * The second review of round 8, class D, built fifteen handlers in five projects that main reports
 * and the branch silenced (scratchpad verify-W2-r2/n, p, d, g1 and g2). They are kept here verbatim,
 * with the migrations and helpers they were scanned with, so none of them can go quiet again. Each
 * project also holds the secure shape it is easily mistaken for (`ctrl`, `pctrl`). Fix 3 cut the
 * clearing through a membership check and the caller's-own-rows shortcut, so those twins are
 * reported too, as main reports them; the expectations below are main's findings.
 */
const R2: Record<string, Record<string, string>> = {
  n: {
    "lib/supabase.ts": `import { createClient } from "@supabase/supabase-js";

/**
 * "Server-side helper" as commonly generated by AI tools: a single service-role client
 * reused for every request. The service role bypasses Row Level Security entirely.
 */
export function createServiceRoleClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { persistSession: false } },
  );
}

export async function getUserFromRequest(req: Request) {
  const auth = req.headers.get("authorization") ?? "";
  const token = auth.startsWith("Bearer ") ? auth.slice(7) : null;
  if (!token) return null;
  const { data, error } = await createServiceRoleClient().auth.getUser(token);
  if (error || !data.user) return null;
  return data.user;
}
`,
    "lib/http.ts": `import { NextResponse } from "next/server";

export function unauthorized(message = "Unauthorized") {
  return NextResponse.json({ error: message }, { status: 401 });
}

export function forbidden(message = "Forbidden") {
  return NextResponse.json({ error: message }, { status: 403 });
}
`,
    "supabase/migrations/0001_init.sql": `create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null);
create table public.organization_members (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  primary key (organization_id, user_id)
);
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  owner_id uuid references auth.users (id),
  shared boolean not null default false,
  name text not null,
  created_at timestamptz not null default now()
);
create table public.project_members (
  project_id uuid not null references public.projects (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  primary key (project_id, user_id)
);
create table public.invoices (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  amount numeric not null
);
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.projects enable row level security;
alter table public.project_members enable row level security;
alter table public.invoices enable row level security;
create policy "members: read own rows" on public.organization_members for select to authenticated using (user_id = auth.uid());
create policy "projects: members read" on public.projects for select to authenticated
  using (exists (select 1 from public.organization_members m where m.organization_id = projects.organization_id and m.user_id = auth.uid()));
`,
    "app/api/ctrl/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

// Control: the secure shape. The branch should clear the projects read.
export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const admin = createServiceRoleClient();
  const { data: member } = await admin
    .from("organization_members")
    .select("role")
    .eq("organization_id", orgId)
    .eq("user_id", user.id)
    .maybeSingle();
  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const { data } = await admin.from("projects").select("*").eq("organization_id", orgId);
  return NextResponse.json({ projects: data });
}
`,
    "app/api/n1/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

function forbidden() {
  return NextResponse.json({ error: "Forbidden" }, { status: 403 });
}

export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const admin = createServiceRoleClient();
  const { data: member } = await admin
    .from("organization_members")
    .select("role")
    .eq("organization_id", orgId)
    .eq("user_id", user.id)
    .maybeSingle();
  if (!member) forbidden();
  const { data } = await admin.from("projects").select("*").eq("organization_id", orgId);
  return NextResponse.json({ projects: data });
}
`,
    "app/api/n2/route.ts": `import { NextResponse } from "next/server";
import { forbidden } from "@/lib/http";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const admin = createServiceRoleClient();
  const { data: member } = await admin
    .from("organization_members")
    .select("role")
    .eq("organization_id", orgId)
    .eq("user_id", user.id)
    .maybeSingle();
  if (!member) {
    console.warn("not a member", user.id, orgId);
    forbidden("Not a member of this organization");
  }
  const { data } = await admin.from("invoices").select("*").eq("organization_id", orgId);
  return NextResponse.json({ invoices: data });
}
`,
    "app/api/n3/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

// "Is the caller on any project of this organization?" The filter on project_members.user_id only
// filters the embedded rows (no !inner), so any organization with a project passes.
export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const admin = createServiceRoleClient();
  const { data: mine } = await admin
    .from("projects")
    .select("id, project_members(user_id)")
    .eq("organization_id", orgId)
    .eq("project_members.user_id", user.id)
    .limit(1);
  if (!mine?.length) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const { data } = await admin.from("invoices").select("*").eq("organization_id", orgId);
  return NextResponse.json({ invoices: data });
}
`,
    "app/api/n4/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const body = await req.json();
  const admin = createServiceRoleClient();
  const { data: member } = await admin
    .from("organization_members")
    .select("role")
    .eq("organization_id", body.orgId)
    .eq("user_id", user.id)
    .maybeSingle();
  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const opts = body;
  if (opts.compareWith) opts.orgId = opts.compareWith;
  const { data } = await admin.from("projects").select("*").eq("organization_id", body.orgId);
  return NextResponse.json({ projects: data });
}
`,
    "app/api/n5/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

function applyDefaults(input: { orgId?: string; targetOrgId?: string }) {
  if (input.targetOrgId) input.orgId = input.targetOrgId;
}

export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const body = await req.json();
  const admin = createServiceRoleClient();
  const { data: member } = await admin
    .from("organization_members")
    .select("role")
    .eq("organization_id", body.orgId)
    .eq("user_id", user.id)
    .maybeSingle();
  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  applyDefaults(body);
  const { data } = await admin.from("projects").select("*").eq("organization_id", body.orgId);
  return NextResponse.json({ projects: data });
}
`,
    "app/api/n6/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const admin = createServiceRoleClient();
  const { data: mine } = await admin
    .from("organization_members")
    .select("role")
    .eq("user_id", user.id)
    .limit(1)
    .maybeSingle();
  let q = admin.from("projects").select("*").eq("organization_id", orgId);
  q = mine?.role === "owner" ? q : q.eq("owner_id", user.id);
  const { data } = await q;
  return NextResponse.json({ projects: data });
}
`,
    "app/api/n7/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const admin = createServiceRoleClient();
  const { data: mine } = await admin
    .from("organization_members")
    .select("role")
    .eq("user_id", user.id)
    .limit(1)
    .maybeSingle();
  let q = admin.from("projects").select("*").eq("organization_id", orgId);
  switch (mine?.role) {
    case "owner":
    case "admin":
      break;
    default:
      q = q.eq("owner_id", user.id);
  }
  const { data } = await q;
  return NextResponse.json({ projects: data });
}
`,
    "app/api/n8/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const admin = createServiceRoleClient();
  const { data: mine } = await admin
    .from("organization_members")
    .select("role")
    .eq("user_id", user.id)
    .limit(1)
    .maybeSingle();
  let q = admin.from("projects").select("*").eq("organization_id", orgId);
  if (mine?.role === "owner") {
    const { data } = await q;
    return NextResponse.json({ projects: data });
  }
  q = q.eq("owner_id", user.id);
  const { data } = await q;
  return NextResponse.json({ projects: data });
}
`,
    "app/api/n9/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

// The stop tests a second \`member\` that falls back to a guest row: it never fires.
export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const admin = createServiceRoleClient();
  const res = await admin
    .from("organization_members")
    .select("role")
    .eq("organization_id", orgId)
    .eq("user_id", user.id)
    .maybeSingle();
  if (res.error) {
    const { data: member } = res;
    console.error("membership lookup failed", member);
  }
  const member = res.data ?? { role: "guest" };
  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const { data } = await admin.from("projects").select("*").eq("organization_id", orgId);
  return NextResponse.json({ projects: data, role: member.role });
}
`,
    "app/api/n10/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

const admin = createServiceRoleClient();

async function loadProjects(input: { orgId: string }) {
  const { data } = await admin.from("projects").select("*").eq("organization_id", input.orgId);
  return data;
}

function pickOrg(input: { orgId: string; viewAs?: string }) {
  if (input.viewAs) input.orgId = input.viewAs;
}

export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const body = await req.json();
  const { data: member } = await admin
    .from("organization_members")
    .select("role")
    .eq("organization_id", body.orgId)
    .eq("user_id", user.id)
    .maybeSingle();
  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  pickOrg(body);
  return NextResponse.json({ projects: await loadProjects(body) });
}
`,
  },
  p: {
    "package.json": `{
  "name": "fixture-014-vulnerable",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev -p 3000",
    "build": "next build",
    "start": "next start -p 3000"
  },
  "dependencies": {
    "@supabase/ssr": "^0.7.0",
    "@supabase/supabase-js": "^2.57.0",
    "next": "^15.5.0",
    "react": "^19.1.0",
    "react-dom": "^19.1.0",
    "@prisma/client": "^6.0.0"
  },
  "devDependencies": {
    "@types/node": "^22.15.0",
    "@types/react": "^19.1.0",
    "typescript": "^5.8.0",
    "prisma": "^6.0.0"
  }
}
`,
    "lib/auth.ts": `import { createClient } from "@supabase/supabase-js";

/** Resolves the caller from the bearer token through Supabase Auth. Identity only; authorization happens in the query. */
export async function getUserFromRequest(req: Request) {
  const auth = req.headers.get("authorization") ?? "";
  const token = auth.startsWith("Bearer ") ? auth.slice(7) : null;
  if (!token) return null;
  const sb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, {
    auth: { persistSession: false },
  });
  const { data, error } = await sb.auth.getUser(token);
  if (error || !data.user) return null;
  return data.user;
}
`,
    "lib/prisma.ts": `import { PrismaClient } from "@prisma/client";

/** One PrismaClient per process. Direct Postgres connection: Supabase RLS does not apply. */
const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };
export const prisma = globalForPrisma.prisma ?? new PrismaClient();
if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
`,
    "prisma/schema.prisma": `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model organizations {
  id   String @id @default(uuid()) @db.Uuid
  name String
}

model organization_members {
  organization_id String @db.Uuid
  user_id         String @db.Uuid
  role            String @default("member")
  email           String?

  @@id([organization_id, user_id])
}

model projects {
  id              String  @id @default(uuid()) @db.Uuid
  organization_id String  @db.Uuid
  owner_id        String? @db.Uuid
  shared          Boolean @default(false)
  name            String
}
`,
    "supabase/migrations/0001_init.sql": `create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null);
create table public.organization_members (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  primary key (organization_id, user_id)
);
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  owner_id uuid references auth.users (id),
  shared boolean not null default false,
  name text not null,
  created_at timestamptz not null default now()
);
create table public.project_members (
  project_id uuid not null references public.projects (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  primary key (project_id, user_id)
);
create table public.invoices (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  amount numeric not null
);
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.projects enable row level security;
alter table public.project_members enable row level security;
alter table public.invoices enable row level security;
create policy "members: read own rows" on public.organization_members for select to authenticated using (user_id = auth.uid());
create policy "projects: members read" on public.projects for select to authenticated
  using (exists (select 1 from public.organization_members m where m.organization_id = projects.organization_id and m.user_id = auth.uid()));
`,
    "app/api/pctrl/route.ts": `import { NextResponse } from "next/server";
import { getUserFromRequest } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

// Control: projects of the org that the caller owns. Safe.
export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const rows = await prisma.projects.findMany({ where: { organization_id: orgId, owner_id: user.id } });
  return NextResponse.json({ projects: rows });
}
`,
    "app/api/p1/route.ts": `import { NextResponse } from "next/server";
import { getUserFromRequest } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

// Projects of ?org= that the caller owns or that are shared: the shared ones of any organization.
export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const rows = await prisma.projects.findMany({
    where: { organization_id: orgId, OR: [{ owner_id: user.id }, { shared: true }] },
  });
  return NextResponse.json({ projects: rows });
}
`,
    "app/api/p2/route.ts": `import { NextResponse } from "next/server";
import { getUserFromRequest } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

// "Teammates' projects": everyone else's projects in ?org=, any organization.
export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const rows = await prisma.projects.findMany({
    where: { organization_id: orgId, NOT: { owner_id: user.id } },
  });
  return NextResponse.json({ projects: rows });
}
`,
    "app/api/p3/route.ts": `import { NextResponse } from "next/server";
import { getUserFromRequest } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

// "Clean up the organization": deletes every project in body.orgId that the caller does not own.
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const body = await req.json();
  const out = await prisma.projects.deleteMany({
    where: { organization_id: body.orgId, NOT: { owner_id: user.id } },
  });
  return NextResponse.json({ deleted: out.count });
}
`,
    "app/api/p4/route.ts": `import { NextResponse } from "next/server";
import { getUserFromRequest } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

// Membership by the caller's id, or by an invite email the request names: any member's email opens the org.
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const body = await req.json();
  const orgId: string = body.orgId;
  const member = await prisma.organization_members.findFirst({
    where: { organization_id: orgId, OR: [{ user_id: user.id }, { email: body.email }] },
  });
  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const rows = await prisma.projects.findMany({ where: { organization_id: orgId } });
  return NextResponse.json({ projects: rows });
}
`,
  },
  d: {
    "package.json": `{
  "name": "fixture-024-vulnerable",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev -p 3000",
    "build": "next build",
    "start": "next start -p 3000"
  },
  "dependencies": {
    "@supabase/ssr": "^0.7.0",
    "@supabase/supabase-js": "^2.57.0",
    "next": "^15.5.0",
    "react": "^19.1.0",
    "react-dom": "^19.1.0",
    "drizzle-orm": "^0.45.2",
    "postgres": "^3.4.0"
  },
  "devDependencies": {
    "@types/node": "^22.15.0",
    "@types/react": "^19.1.0",
    "typescript": "^5.8.0"
  }
}
`,
    "lib/auth.ts": `import { createClient } from "@supabase/supabase-js";

/** Resolves the caller from the bearer token through Supabase Auth. Identity only; authorization happens in the query. */
export async function getUserFromRequest(req: Request) {
  const auth = req.headers.get("authorization") ?? "";
  const token = auth.startsWith("Bearer ") ? auth.slice(7) : null;
  if (!token) return null;
  const sb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, {
    auth: { persistSession: false },
  });
  const { data, error } = await sb.auth.getUser(token);
  if (error || !data.user) return null;
  return data.user;
}
`,
    "lib/db.ts": `import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import * as schema from "@/db/schema";

/**
 * Direct Postgres connection as the database owner. Nothing here goes through PostgREST, so the
 * RLS policies in the migrations never run for these queries.
 */
const client = postgres(process.env.DATABASE_URL!, { prepare: false });
export const db = drizzle(client, { schema });
`,
    "db/schema.ts": `import { boolean, pgTable, text, uuid } from "drizzle-orm/pg-core";

export const organizationMembers = pgTable("organization_members", {
  organizationId: uuid("organization_id").notNull(),
  userId: uuid("user_id").notNull(),
  email: text("email"),
  role: text("role").notNull().default("member"),
});

export const projects = pgTable("projects", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull(),
  ownerId: uuid("owner_id"),
  shared: boolean("shared").notNull().default(false),
  name: text("name").notNull(),
});
`,
    "supabase/migrations/0001_init.sql": `create table public.organization_members (
  organization_id uuid not null,
  user_id uuid not null,
  email text,
  role text not null default 'member',
  primary key (organization_id, user_id)
);
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null,
  owner_id uuid,
  shared boolean not null default false,
  name text not null
);
alter table public.organization_members enable row level security;
alter table public.projects enable row level security;
create policy "members: read own rows" on public.organization_members for select to authenticated using (user_id = auth.uid());
`,
    "app/api/d1/route.ts": `import { and, eq, or } from "drizzle-orm";
import { NextResponse } from "next/server";
import { projects } from "@/db/schema";
import { getUserFromRequest } from "@/lib/auth";
import { db } from "@/lib/db";

// Projects of ?org= that the caller owns or that are shared: the shared ones of any organization.
export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const rows = await db
    .select()
    .from(projects)
    .where(and(eq(projects.organizationId, orgId), or(eq(projects.ownerId, user.id), eq(projects.shared, true))));
  return NextResponse.json({ projects: rows });
}
`,
    "app/api/d2/route.ts": `import { and, eq, not } from "drizzle-orm";
import { NextResponse } from "next/server";
import { projects } from "@/db/schema";
import { getUserFromRequest } from "@/lib/auth";
import { db } from "@/lib/db";

// Deletes every project in body.orgId the caller does not own, in any organization.
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const body = await req.json();
  await db
    .delete(projects)
    .where(and(eq(projects.organizationId, body.orgId), not(eq(projects.ownerId, user.id))));
  return NextResponse.json({ ok: true });
}
`,
    "app/api/d3/route.ts": `import { and, eq, or } from "drizzle-orm";
import { NextResponse } from "next/server";
import { organizationMembers, projects } from "@/db/schema";
import { getUserFromRequest } from "@/lib/auth";
import { db } from "@/lib/db";

// Membership by the caller's id or by an email the request names.
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const body = await req.json();
  const orgId: string = body.orgId;
  const [member] = await db
    .select()
    .from(organizationMembers)
    .where(
      and(
        eq(organizationMembers.organizationId, orgId),
        or(eq(organizationMembers.userId, user.id), eq(organizationMembers.email, body.email)),
      ),
    )
    .limit(1);
  const found = await db.query.organizationMembers.findFirst({
    where: and(
      eq(organizationMembers.organizationId, orgId),
      or(eq(organizationMembers.userId, user.id), eq(organizationMembers.email, body.email)),
    ),
  });
  if (!found) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const rows = await db.select().from(projects).where(eq(projects.organizationId, orgId));
  return NextResponse.json({ projects: rows, member });
}
`,
  },
  g1: {
    "lib/supabase.ts": `import { createClient } from "@supabase/supabase-js";

/**
 * "Server-side helper" as commonly generated by AI tools: a single service-role client
 * reused for every request. The service role bypasses Row Level Security entirely.
 */
export function createServiceRoleClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { persistSession: false } },
  );
}

export async function getUserFromRequest(req: Request) {
  const auth = req.headers.get("authorization") ?? "";
  const token = auth.startsWith("Bearer ") ? auth.slice(7) : null;
  if (!token) return null;
  const { data, error } = await createServiceRoleClient().auth.getUser(token);
  if (error || !data.user) return null;
  return data.user;
}
`,
    "supabase/migrations/0001_init.sql": `create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null);
create table public.organization_members (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  primary key (organization_id, user_id)
);
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  name text not null
);
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.projects enable row level security;
create policy "members: read own rows" on public.organization_members for select to authenticated using (user_id = auth.uid());

-- "Join" button: any signed-in user joins any organization by id.
create or replace function public.join_organization(p_org uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.organization_members (organization_id, user_id, role)
  values (p_org, auth.uid(), 'member')
  on conflict do nothing;
end;
$$;
grant execute on function public.join_organization(uuid) to authenticated;
`,
    "app/api/projects/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

// Control: the secure shape. The branch should clear the projects read.
export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const admin = createServiceRoleClient();
  const { data: member } = await admin
    .from("organization_members")
    .select("role")
    .eq("organization_id", orgId)
    .eq("user_id", user.id)
    .maybeSingle();
  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const { data } = await admin.from("projects").select("*").eq("organization_id", orgId);
  return NextResponse.json({ projects: data });
}
`,
  },
  g2: {
    "lib/supabase.ts": `import { createClient } from "@supabase/supabase-js";

/**
 * "Server-side helper" as commonly generated by AI tools: a single service-role client
 * reused for every request. The service role bypasses Row Level Security entirely.
 */
export function createServiceRoleClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { persistSession: false } },
  );
}

export async function getUserFromRequest(req: Request) {
  const auth = req.headers.get("authorization") ?? "";
  const token = auth.startsWith("Bearer ") ? auth.slice(7) : null;
  if (!token) return null;
  const { data, error } = await createServiceRoleClient().auth.getUser(token);
  if (error || !data.user) return null;
  return data.user;
}
`,
    "supabase/migrations/0001_init.sql": `create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null);
create table public.organization_members (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  primary key (organization_id, user_id)
);
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  owner_id uuid references auth.users (id),
  shared boolean not null default false,
  name text not null,
  created_at timestamptz not null default now()
);
create table public.project_members (
  project_id uuid not null references public.projects (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  primary key (project_id, user_id)
);
create table public.invoices (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  amount numeric not null
);
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.projects enable row level security;
alter table public.project_members enable row level security;
alter table public.invoices enable row level security;
create policy "members: read own rows" on public.organization_members for select to authenticated using (user_id = auth.uid());
create policy "projects: members read" on public.projects for select to authenticated
  using (exists (select 1 from public.organization_members m where m.organization_id = projects.organization_id and m.user_id = auth.uid()));
`,
    "app/api/projects/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

// Control: the secure shape. The branch should clear the projects read.
export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const admin = createServiceRoleClient();
  const { data: member } = await admin
    .from("organization_members")
    .select("role")
    .eq("organization_id", orgId)
    .eq("user_id", user.id)
    .maybeSingle();
  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const { data } = await admin.from("projects").select("*").eq("organization_id", orgId);
  return NextResponse.json({ projects: data });
}
`,
    "app/api/join/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

// Joins the caller to the organization in the body. No invite is checked.
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { organizationId } = await req.json();
  const admin = createServiceRoleClient();
  const { error } = await admin
    .from("organization_members")
    .insert({ organization_id: organizationId, user_id: user.id, role: "member" });
  if (error) return NextResponse.json({ error: "Failed" }, { status: 500 });
  return NextResponse.json({ ok: true });
}
`,
  },
};

interface Hit {
  file: string;
  line: number;
  severity: string;
}

const scans = new Map<string, Hit[]>();

/** R4 findings of one counterexample project: the query each points at, and its severity. */
function r4(project: string, extra: Record<string, string> = {}): Hit[] {
  const key = `${project}\u0000${JSON.stringify(extra)}`;
  const cached = scans.get(key);
  if (cached) return cached;
  const dir = mkdtempSync(join(tmpdir(), `auditai-ownership-r2-${project}-`));
  for (const [rel, text] of Object.entries({ ...R2[project], ...extra })) {
    mkdirSync(dirname(join(dir, rel)), { recursive: true });
    writeFileSync(join(dir, rel), text);
  }
  const model = parseProject(dir);
  const hits = runRules([userControlledTenantScope], model, buildGraph(model), {
    now: "2026-09-23T00:00:00Z",
  })
    .map((f) => {
      const at = f.evidence[0]?.locations?.[1];
      return { file: at?.file ?? "", line: at?.line ?? 0, severity: f.severity };
    })
    .sort((a, b) => a.file.localeCompare(b.file) || a.line - b.line);
  scans.set(key, hits);
  return hits;
}

/** The query lines R4 reports in one route file of a project. */
function lines(project: string, route: string, extra: Record<string, string> = {}): number[] {
  return r4(project, extra)
    .filter((h) => h.file === `app/api/${route}/route.ts`)
    .map((h) => h.line);
}

describe("second review, project n: supabase-js with the service role", () => {
  it("control: the membership check that dominates the read is reported, as on main", () => {
    expect(lines("n", "ctrl")).toEqual([11, 18]);
  });

  it("n1: a local `forbidden()` that returns a Response, called without `return`, stops nothing", () => {
    expect(lines("n", "n1")).toEqual([14, 21]);
  });

  it("n2: a repository `forbidden()` as the last statement of the block stops nothing", () => {
    expect(lines("n", "n2")).toEqual([11, 21]);
  });

  it("n3: a filter on an embedded resource's column does not key the lookup by the caller", () => {
    // Without !inner PostgREST filters only the embedded rows: any organization with a project passes.
    expect(lines("n", "n3")).toEqual([12, 19]);
  });

  it("n4: the tenant written through an alias of the request body is not the one checked", () => {
    expect(lines("n", "n4")).toEqual([9, 18]);
  });

  it("n5: the request body handed to a helper that rewrites the tenant is not the one checked", () => {
    expect(lines("n", "n5")).toEqual([13, 21]);
  });

  it("n10: the body a helper rewrites before it reaches the query's helper is not the one checked", () => {
    expect(lines("n", "n10")).toEqual([7, 19]);
  });

  it("n6, n7, n8: an owner filter added to a saved builder on some paths only does not make the rows the caller's", () => {
    // A ternary, a switch, and an early return that runs the builder before the filter is added.
    expect(lines("n", "n6")).toEqual([16]);
    expect(lines("n", "n7")).toEqual([16]);
    expect(lines("n", "n8")).toEqual([16]);
  });

  it("n9: a stop that tests a second, always-truthy binding of the row's name stops nothing", () => {
    expect(lines("n", "n9")).toEqual([11, 23]);
  });
});

describe("second review, project p: Prisma, OR and NOT are not the caller's own rows", () => {
  it("control: the caller's id as a plain where key is reported, as on main", () => {
    expect(lines("p", "pctrl")).toEqual([11]);
  });

  it("p1: `OR: [{ owner_id: user.id }, { shared: true }]` returns every shared row of any organization", () => {
    expect(lines("p", "p1")).toEqual([11]);
  });

  it("p2, p3: `NOT: { owner_id: user.id }` is everyone else's rows, read or deleted", () => {
    expect(lines("p", "p2")).toEqual([11]);
    expect(lines("p", "p3")).toEqual([10]);
  });

  it("p4: a membership read by the caller's id OR an email the request names proves nothing", () => {
    expect(lines("p", "p4")).toEqual([11, 15]);
  });
});

describe("second review, project d: Drizzle, or() and not() are not the caller's own rows", () => {
  it("d1: `or(eq(ownerId, user.id), eq(shared, true))`", () => {
    expect(lines("d", "d1")).toEqual([13]);
  });

  it("d2: `not(eq(ownerId, user.id))` in a delete", () => {
    expect(lines("d", "d2")).toEqual([12]);
  });

  it("d3: a membership read by the caller's id or an email the request names proves nothing", () => {
    expect(lines("d", "d3")).toEqual([13, 23, 30]);
  });
});

describe("second review, g1 and g2: a membership callers grant themselves outside the policies", () => {
  it("g1: a SECURITY DEFINER function any signed-in user may call inserts the membership row", () => {
    expect(r4("g1")).toEqual([
      {
        file: "app/api/projects/route.ts",
        line: 11,
        severity: "critical",
      },
      {
        file: "app/api/projects/route.ts",
        line: 18,
        severity: "critical",
      },
    ]);
    // The secure twin: the same function, executable by no API role.
    const revoked = `${R2.g1?.["supabase/migrations/0001_init.sql"] ?? ""}revoke execute on function public.join_organization(uuid) from public, anon, authenticated;
`;
    expect(r4("g1", { "supabase/migrations/0001_init.sql": revoked })).toEqual([
      {
        file: "app/api/projects/route.ts",
        line: 11,
        severity: "critical",
      },
      {
        file: "app/api/projects/route.ts",
        line: 18,
        severity: "critical",
      },
    ]);
  });

  it("g2: a service-role insert of the membership row for the organization the body names", () => {
    expect(r4("g2")).toEqual([
      {
        file: "app/api/projects/route.ts",
        line: 11,
        severity: "critical",
      },
      {
        file: "app/api/projects/route.ts",
        line: 18,
        severity: "critical",
      },
    ]);
    // The secure twin: the organization joined is the one an invitation row names.
    const invited = `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { token } = await req.json();
  const admin = createServiceRoleClient();
  const { data: invite } = await admin
    .from("invitations")
    .select("organization_id")
    .eq("token", token)
    .maybeSingle();
  if (!invite) return NextResponse.json({ error: "Not found" }, { status: 404 });
  const { error } = await admin
    .from("organization_members")
    .insert({ organization_id: invite.organization_id, user_id: user.id, role: "member" });
  if (error) return NextResponse.json({ error: "Failed" }, { status: 500 });
  return NextResponse.json({ ok: true });
}
`;
    expect(r4("g2", { "app/api/join/route.ts": invited })).toEqual([
      {
        file: "app/api/projects/route.ts",
        line: 11,
        severity: "critical",
      },
      {
        file: "app/api/projects/route.ts",
        line: 18,
        severity: "critical",
      },
    ]);
  });
});

/** A handler of project n: the caller's membership of `orgId` read, then `after` runs. */
function membershipRoute(head: string, beforeRead: string, after: string): string {
  return `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";
${head}
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const body = await req.json();
  const admin = createServiceRoleClient();
${beforeRead}
  const { data: member } = await admin
    .from("organization_members")
    .select("role")
    .eq("organization_id", body.orgId)
    .eq("user_id", user.id)
    .maybeSingle();
${after}
}
`;
}

/** R4 lines of one extra route added to project n. */
function twin(route: string): number[] {
  return lines("n", "twin", { "app/api/twin/route.ts": route });
}

describe("second review: the secure twins, reported since fix 3 cut the clearing", () => {
  const QUERY = `  const { data } = await admin.from("projects").select("*").eq("organization_id", body.orgId);
  return NextResponse.json({ projects: data });`;

  it("n1, n2: `forbidden()` and `notFound()` from next/navigation throw, by name or namespace", () => {
    expect(
      twin(
        membershipRoute(
          `import { forbidden } from "next/navigation";`,
          "",
          `  if (!member) forbidden();\n${QUERY}`,
        ),
      ),
    ).toEqual([10, 17]);
    expect(
      twin(
        membershipRoute(
          `import * as nav from "next/navigation";`,
          "",
          `  if (!member) {\n    console.warn("not a member");\n    nav.notFound();\n  }\n${QUERY}`,
        ),
      ),
    ).toEqual([10, 20]);
    // Imported from next/navigation, but a parameter of the same name rebinds it in this file.
    expect(
      twin(
        membershipRoute(
          `import { forbidden } from "next/navigation";
const deny = (forbidden: () => void) => forbidden;`,
          "",
          `  if (!member) forbidden();\n${QUERY}`,
        ),
      ),
    ).toEqual([11, 18]);
  });

  it("n4, n5, n10: a copy of the body, or a call that only reads it, leaves the tenant as checked", () => {
    expect(
      twin(
        membershipRoute(
          "",
          "",
          `  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const opts = { ...body };
  if (opts.compareWith) opts.orgId = opts.compareWith;
  console.log(JSON.stringify(body));
${QUERY}`,
        ),
      ),
    ).toEqual([10, 20]);
    // The body handed to a helper after the query cannot change what the query read.
    expect(
      twin(
        membershipRoute(
          `function audit(input: { orgId?: string }) { input.orgId = undefined; }`,
          "",
          `  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const { data } = await admin.from("projects").select("*").eq("organization_id", body.orgId);
  audit(body);
  return NextResponse.json({ projects: data });`,
        ),
      ),
    ).toEqual([10, 17]);
    // The same helper before the query: the tenant it may rewrite is not the one checked.
    expect(
      twin(
        membershipRoute(
          `function audit(input: { orgId?: string }) { input.orgId = undefined; }`,
          "",
          `  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  audit(body);
${QUERY}`,
        ),
      ),
    ).toEqual([10, 18]);
    // Inside a loop the next turn's query runs after the helper.
    expect(
      twin(
        membershipRoute(
          `function audit(input: { orgId?: string }) { input.orgId = undefined; }`,
          "",
          `  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  for (const _ of [1, 2]) {
    await admin.from("projects").select("*").eq("organization_id", body.orgId);
    audit(body);
  }
  return NextResponse.json({});`,
        ),
      ),
    ).toEqual([10, 18]);
  });

  it("n9: the row name the stop tests is the lookup's own binding, not a module-level one", () => {
    const route = (binding: string) => `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

const member = { role: "guest" };

export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  const admin = createServiceRoleClient();
  const res = await admin
    .from("organization_members")
    .select("role")
    .eq("organization_id", orgId)
    .eq("user_id", user.id)
    .maybeSingle();
${binding}
  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const { data } = await admin.from("projects").select("*").eq("organization_id", orgId);
  return NextResponse.json({ projects: data, role: member.role });
}
`;
    // The lookup's row is bound only inside the error branch: the stop tests the module's guest.
    expect(
      twin(
        route(
          `  if (res.error) {\n    const { data: member } = res;\n    console.error(member);\n  }`,
        ),
      ),
    ).toEqual([11, 22]);
    // Bound in the handler's own block before the stop, it is the row.
    expect(twin(route(`  const { data: member } = res;`))).toEqual([11, 19]);
  });

  it("p, d: the caller's id in AND or and() is a top-level filter", () => {
    expect(
      lines("p", "twin", {
        "app/api/twin/route.ts": `import { NextResponse } from "next/server";
import { getUserFromRequest } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const rows = await prisma.projects.findMany({
    where: { AND: [{ organization_id: orgId }, { owner_id: user.id }] },
  });
  return NextResponse.json({ projects: rows });
}
`,
      }),
    ).toEqual([10]);
    expect(
      lines("d", "twin", {
        "app/api/twin/route.ts": `import { and, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { projects } from "@/db/schema";
import { getUserFromRequest } from "@/lib/auth";
import { db } from "@/lib/db";

export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const rows = await db
    .select()
    .from(projects)
    .where(and(eq(projects.organizationId, orgId), eq(projects.ownerId, user.id)));
  return NextResponse.json({ projects: rows });
}
`,
      }),
    ).toEqual([12]);
  });

  it("n6: an owner filter added to a saved builder is not read, even on straight-line code", () => {
    // The simplest safe reading the review allowed: only the query's own chain counts for `own`.
    expect(
      twin(`import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  const admin = createServiceRoleClient();
  let q = admin.from("projects").select("*").eq("organization_id", orgId);
  q = q.eq("owner_id", user.id);
  const { data } = await q;
  return NextResponse.json({ projects: data });
}
`),
    ).toEqual([9]);
  });
});

describe("second review: variants found while closing it", () => {
  it("g1 without a GRANT: Supabase lets anon and authenticated execute a new function by default", () => {
    const sql = (R2.g1?.["supabase/migrations/0001_init.sql"] ?? "").replace(
      /^grant execute.*$/m,
      "",
    );
    expect(r4("g1", { "supabase/migrations/0001_init.sql": sql })).toEqual([
      {
        file: "app/api/projects/route.ts",
        line: 11,
        severity: "critical",
      },
      {
        file: "app/api/projects/route.ts",
        line: 18,
        severity: "critical",
      },
    ]);
  });

  it("g2 through a map over the body, or a repository helper, still writes a requested tenant", () => {
    const mapped = `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const body = await req.json();
  const rows = (body.orgIds as string[]).map((id) => ({ organization_id: id, user_id: user.id }));
  const admin = createServiceRoleClient();
  await admin.from("organization_members").insert(rows);
  return NextResponse.json({ ok: true });
}
`;
    expect(r4("g2", { "app/api/join/route.ts": mapped })).toEqual([
      {
        file: "app/api/projects/route.ts",
        line: 11,
        severity: "critical",
      },
      {
        file: "app/api/projects/route.ts",
        line: 18,
        severity: "critical",
      },
    ]);
    const lib = `${R2.g2?.["lib/supabase.ts"] ?? ""}
export async function addMember(orgId: string, userId: string) {
  return createServiceRoleClient().from("organization_members").insert({ organization_id: orgId, user_id: userId });
}
`;
    const viaHelper = `import { NextResponse } from "next/server";
import { addMember, getUserFromRequest } from "@/lib/supabase";
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { orgId } = await req.json();
  await addMember(orgId, user.id);
  return NextResponse.json({ ok: true });
}
`;
    expect(r4("g2", { "lib/supabase.ts": lib, "app/api/join/route.ts": viaHelper })).toEqual([
      {
        file: "app/api/projects/route.ts",
        line: 11,
        severity: "critical",
      },
      {
        file: "app/api/projects/route.ts",
        line: 18,
        severity: "critical",
      },
    ]);
  });

  it("n10 with the helper's promise kept: the caller rewrites the body while the helper awaits", () => {
    const route = (call: string) => `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";
const admin = createServiceRoleClient();
async function loadProjects(input: { orgId: string }) {
  await Promise.resolve();
  const { data } = await admin.from("projects").select("*").eq("organization_id", input.orgId);
  return data;
}
function pickOrg(input: { orgId: string; viewAs?: string }) {
  if (input.viewAs) input.orgId = input.viewAs;
}
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const body = await req.json();
  const { data: member } = await admin.from("organization_members").select("role").eq("organization_id", body.orgId).eq("user_id", user.id).maybeSingle();
  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
${call}
}
`;
    expect(
      twin(
        route(
          "  const pending = loadProjects(body);\n  pickOrg(body);\n  return NextResponse.json({ projects: await pending });",
        ),
      ),
    ).toEqual([6, 16]);
    // Awaited, the helper has read the tenant before the caller rewrites it.
    expect(
      twin(
        route(
          "  const projects = await loadProjects(body);\n  pickOrg(body);\n  return NextResponse.json({ projects });",
        ),
      ),
    ).toEqual([6, 16]);
  });

  it("n10 with the body handed to two parameters: the other one may rewrite the tenant", () => {
    expect(
      twin(`import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";
const admin = createServiceRoleClient();
async function loadProjects(input: { orgId: string }, other: { orgId: string; viewAs?: string }) {
  if (other.viewAs) other.orgId = other.viewAs;
  const { data } = await admin.from("projects").select("*").eq("organization_id", input.orgId);
  return data;
}
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const body = await req.json();
  const { data: member } = await admin.from("organization_members").select("role").eq("organization_id", body.orgId).eq("user_id", user.id).maybeSingle();
  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  return NextResponse.json({ projects: await loadProjects(body, body) });
}
`),
    ).toEqual([6, 13]);
  });
});
