import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { buildGraph } from "@auditai/graph";
import { parseProject } from "@auditai/parser";
import { describe, expect, it } from "vitest";
import { runRules } from "../rule.js";
import { userControlledTenantScope } from "./supabase-authorization.js";

/**
 * The third review of round 8, class D, found seventeen more handlers the branch silenced while main
 * reports them (scratchpad verify-W2-r3): membership rows granted outside the policies the branch
 * read (triggers, rpc, Prisma nested writes, piecewise payloads, deep helpers, Edge Functions, user
 * metadata, DO blocks, ALTER POLICY), identity resolved by name through a shadowing loop or callback
 * variable, and a tenant rewritten through Object.values. Fix 3 answered by cutting the clearing
 * through a membership check and the caller's-own-rows shortcut from the branch, not by listing more
 * shapes. Every project is kept here verbatim, each reported exactly where main reports it, next to
 * the twins the review scanned with it (ctrl0, pz0, s3, j2, d3, d4, d5, c1), which main reports too.
 */
const BASE: Record<string, string> = {
  "app/api/projects/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

// Projects of an organization the caller is a member of.
export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const admin = createServiceRoleClient();
  const { data: member } = await admin
    .from("organization_members")
    .select("role")
    .eq("organization_id", orgId)
    .eq("user_id", user.id)
    .maybeSingle();
  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const { data } = await admin.from("projects").select("*").eq("organization_id", orgId);
  return NextResponse.json({ projects: data });
}
`,
  "lib/supabase.ts": `import { createClient } from "@supabase/supabase-js";

/**
 * "Server-side helper" as commonly generated by AI tools: a single service-role client
 * reused for every request. The service role bypasses Row Level Security entirely.
 */
export function createServiceRoleClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { persistSession: false } },
  );
}

export async function getUserFromRequest(req: Request) {
  const auth = req.headers.get("authorization") ?? "";
  const token = auth.startsWith("Bearer ") ? auth.slice(7) : null;
  if (!token) return null;
  const { data, error } = await createServiceRoleClient().auth.getUser(token);
  if (error || !data.user) return null;
  return data.user;
}
`,
  "package.json": `{
  "name": "fixture-042-vulnerable",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev -p 3000",
    "build": "next build",
    "start": "next start -p 3000"
  },
  "dependencies": {
    "@supabase/ssr": "^0.7.0",
    "@supabase/supabase-js": "^2.57.0",
    "next": "^15.5.0",
    "react": "^19.1.0",
    "react-dom": "^19.1.0"
  },
  "devDependencies": {
    "@types/node": "^22.15.0",
    "@types/react": "^19.1.0",
    "typescript": "^5.8.0"
  }
}
`,
  "supabase/migrations/0001_init.sql": `create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text unique);
create table public.organization_members (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  primary key (organization_id, user_id)
);
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  name text not null
);
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.projects enable row level security;
create policy "members: read own rows" on public.organization_members for select to authenticated using (user_id = auth.uid());
`,
  "tsconfig.json": `{
  "compilerOptions": {
    "target": "ES2022",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "strict": true,
    "noEmit": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "jsx": "preserve",
    "isolatedModules": true,
    "skipLibCheck": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": [
        "./*"
      ]
    }
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
`,
};

/** Each project as the review built it: the files it adds to or changes in BASE, null for one it drops. */
const R3: Record<string, Record<string, string | null>> = {
  t1: {
    "supabase/migrations/0001_init.sql": `create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text unique);
create table public.organization_members (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  primary key (organization_id, user_id)
);
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  name text not null
);
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.projects enable row level security;
create policy "members: read own rows" on public.organization_members for select to authenticated using (user_id = auth.uid());

-- Invite links carry the organization in the sign-up metadata: supabase.auth.signUp({ email, password,
-- options: { data: { organization_id } } }). The new user is added to that organization on sign-up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.raw_user_meta_data ? 'organization_id' then
    insert into public.organization_members (organization_id, user_id, role)
    values ((new.raw_user_meta_data ->> 'organization_id')::uuid, new.id, 'member')
    on conflict do nothing;
  end if;
  return new;
end;
$$;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
`,
  },
  t2: {
    "supabase/migrations/0001_init.sql": `create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text unique);
create table public.organization_members (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  primary key (organization_id, user_id)
);
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  name text not null
);
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.projects enable row level security;
create policy "members: read own rows" on public.organization_members for select to authenticated using (user_id = auth.uid());

-- Open organizations: a join request is accepted at once.
create table public.join_requests (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.join_requests enable row level security;
create policy "join_requests: insert own" on public.join_requests for insert to authenticated
  with check (user_id = auth.uid());
create or replace function public.accept_join_request()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.organization_members (organization_id, user_id, role)
  values (new.organization_id, new.user_id, 'member')
  on conflict do nothing;
  return new;
end;
$$;
create trigger join_requests_accept
  after insert on public.join_requests
  for each row execute function public.accept_join_request();
`,
  },
  r1: {
    "app/api/join/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

// Joins the caller to the organization in the body. No invite is checked.
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { organizationId } = await req.json();
  const admin = createServiceRoleClient();
  const { error } = await admin.rpc("add_organization_member", {
    p_organization_id: organizationId,
    p_user_id: user.id,
  });
  if (error) return NextResponse.json({ error: "Failed" }, { status: 500 });
  return NextResponse.json({ ok: true });
}
`,
    "supabase/migrations/0001_init.sql": `create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text unique);
create table public.organization_members (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  primary key (organization_id, user_id)
);
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  name text not null
);
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.projects enable row level security;
create policy "members: read own rows" on public.organization_members for select to authenticated using (user_id = auth.uid());

-- Adds a member. Only the server (service role) may call it.
create or replace function public.add_organization_member(p_organization_id uuid, p_user_id uuid, p_role text default 'member')
returns void
language sql
as $$
  insert into public.organization_members (organization_id, user_id, role)
  values (p_organization_id, p_user_id, p_role)
  on conflict do nothing;
$$;
revoke execute on function public.add_organization_member(uuid, uuid, text) from public, anon, authenticated;
grant execute on function public.add_organization_member(uuid, uuid, text) to service_role;
`,
  },
  r2: {
    "app/api/join/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

// Joins the caller to the organization in the body. No invite is checked.
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { organizationId } = await req.json();
  const admin = createServiceRoleClient();
  const { error } = await admin.rpc("add_organization_member", {
    p_organization_id: organizationId,
    p_user_id: user.id,
  });
  if (error) return NextResponse.json({ error: "Failed" }, { status: 500 });
  return NextResponse.json({ ok: true });
}
`,
    "supabase/migrations/0001_init.sql": `create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text unique);
create table public.organization_members (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  primary key (organization_id, user_id)
);
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  name text not null
);
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.projects enable row level security;
create policy "members: read own rows" on public.organization_members for select to authenticated using (user_id = auth.uid());

create or replace function public.add_organization_member(p_organization_id uuid, p_user_id uuid, p_role text default 'member')
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.organization_members (organization_id, user_id, role)
  values (p_organization_id, p_user_id, p_role)
  on conflict do nothing;
end;
$$;
revoke execute on function public.add_organization_member(uuid, uuid, text) from public, anon, authenticated;
`,
  },
  pz1: {
    "app/api/join/route.ts": `import { NextResponse } from "next/server";
import { getUserFromRequest } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

// Joins the caller to the organization in the body. No invite is checked.
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const body = await req.json();
  await prisma.organization_members.create({
    data: { organization: { connect: { id: body.organizationId } }, user_id: user.id, role: "member" },
  });
  return NextResponse.json({ ok: true });
}
`,
    "app/api/projects/route.ts": `import { NextResponse } from "next/server";
import { getUserFromRequest } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

// Projects of an organization the caller is a member of.
export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const member = await prisma.organization_members.findFirst({
    where: { organization_id: orgId, user_id: user.id },
  });
  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const rows = await prisma.projects.findMany({ where: { organization_id: orgId } });
  return NextResponse.json({ projects: rows });
}
`,
    "lib/auth.ts": `import { createClient } from "@supabase/supabase-js";

/** Resolves the caller from the bearer token through Supabase Auth. Identity only; authorization happens in the query. */
export async function getUserFromRequest(req: Request) {
  const auth = req.headers.get("authorization") ?? "";
  const token = auth.startsWith("Bearer ") ? auth.slice(7) : null;
  if (!token) return null;
  const sb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, {
    auth: { persistSession: false },
  });
  const { data, error } = await sb.auth.getUser(token);
  if (error || !data.user) return null;
  return data.user;
}
`,
    "lib/prisma.ts": `import { PrismaClient } from "@prisma/client";

/** One PrismaClient per process. Direct Postgres connection: Supabase RLS does not apply. */
const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };
export const prisma = globalForPrisma.prisma ?? new PrismaClient();
if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
`,
    "package.json": `{
  "name": "fixture-014-vulnerable",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev -p 3000",
    "build": "next build",
    "start": "next start -p 3000"
  },
  "dependencies": {
    "@supabase/ssr": "^0.7.0",
    "@supabase/supabase-js": "^2.57.0",
    "next": "^15.5.0",
    "react": "^19.1.0",
    "react-dom": "^19.1.0",
    "@prisma/client": "^6.0.0"
  },
  "devDependencies": {
    "@types/node": "^22.15.0",
    "@types/react": "^19.1.0",
    "typescript": "^5.8.0",
    "prisma": "^6.0.0"
  }
}
`,
    "prisma/schema.prisma": `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model organizations {
  id      String                 @id @default(uuid()) @db.Uuid
  name    String
  members organization_members[]
}

model organization_members {
  organization_id String        @db.Uuid
  user_id         String        @db.Uuid
  role            String        @default("member")
  organization    organizations @relation(fields: [organization_id], references: [id])

  @@id([organization_id, user_id])
}

model projects {
  id              String  @id @default(uuid()) @db.Uuid
  organization_id String  @db.Uuid
  owner_id        String? @db.Uuid
  shared          Boolean @default(false)
  name            String
}
`,
    "supabase/migrations/0001_init.sql": `create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null);
create table public.organization_members (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  primary key (organization_id, user_id)
);
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  owner_id uuid references auth.users (id),
  shared boolean not null default false,
  name text not null,
  created_at timestamptz not null default now()
);
create table public.project_members (
  project_id uuid not null references public.projects (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  primary key (project_id, user_id)
);
create table public.invoices (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  amount numeric not null
);
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.projects enable row level security;
alter table public.project_members enable row level security;
alter table public.invoices enable row level security;
create policy "members: read own rows" on public.organization_members for select to authenticated using (user_id = auth.uid());
create policy "projects: members read" on public.projects for select to authenticated
  using (exists (select 1 from public.organization_members m where m.organization_id = projects.organization_id and m.user_id = auth.uid()));
`,
    "lib/supabase.ts": null,
  },
  pz2: {
    "app/api/join/route.ts": `import { NextResponse } from "next/server";
import { getUserFromRequest } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

// Joins the caller to the organization in the body. No invite is checked.
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const body = await req.json();
  await prisma.organizations.update({
    where: { id: body.organizationId },
    data: { members: { create: { user_id: user.id, role: "member" } } },
  });
  return NextResponse.json({ ok: true });
}
`,
    "app/api/projects/route.ts": `import { NextResponse } from "next/server";
import { getUserFromRequest } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

// Projects of an organization the caller is a member of.
export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const member = await prisma.organization_members.findFirst({
    where: { organization_id: orgId, user_id: user.id },
  });
  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const rows = await prisma.projects.findMany({ where: { organization_id: orgId } });
  return NextResponse.json({ projects: rows });
}
`,
    "lib/auth.ts": `import { createClient } from "@supabase/supabase-js";

/** Resolves the caller from the bearer token through Supabase Auth. Identity only; authorization happens in the query. */
export async function getUserFromRequest(req: Request) {
  const auth = req.headers.get("authorization") ?? "";
  const token = auth.startsWith("Bearer ") ? auth.slice(7) : null;
  if (!token) return null;
  const sb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, {
    auth: { persistSession: false },
  });
  const { data, error } = await sb.auth.getUser(token);
  if (error || !data.user) return null;
  return data.user;
}
`,
    "lib/prisma.ts": `import { PrismaClient } from "@prisma/client";

/** One PrismaClient per process. Direct Postgres connection: Supabase RLS does not apply. */
const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };
export const prisma = globalForPrisma.prisma ?? new PrismaClient();
if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
`,
    "package.json": `{
  "name": "fixture-014-vulnerable",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev -p 3000",
    "build": "next build",
    "start": "next start -p 3000"
  },
  "dependencies": {
    "@supabase/ssr": "^0.7.0",
    "@supabase/supabase-js": "^2.57.0",
    "next": "^15.5.0",
    "react": "^19.1.0",
    "react-dom": "^19.1.0",
    "@prisma/client": "^6.0.0"
  },
  "devDependencies": {
    "@types/node": "^22.15.0",
    "@types/react": "^19.1.0",
    "typescript": "^5.8.0",
    "prisma": "^6.0.0"
  }
}
`,
    "prisma/schema.prisma": `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model organizations {
  id      String                 @id @default(uuid()) @db.Uuid
  name    String
  members organization_members[]
}

model organization_members {
  organization_id String        @db.Uuid
  user_id         String        @db.Uuid
  role            String        @default("member")
  organization    organizations @relation(fields: [organization_id], references: [id])

  @@id([organization_id, user_id])
}

model projects {
  id              String  @id @default(uuid()) @db.Uuid
  organization_id String  @db.Uuid
  owner_id        String? @db.Uuid
  shared          Boolean @default(false)
  name            String
}
`,
    "supabase/migrations/0001_init.sql": `create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null);
create table public.organization_members (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  primary key (organization_id, user_id)
);
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  owner_id uuid references auth.users (id),
  shared boolean not null default false,
  name text not null,
  created_at timestamptz not null default now()
);
create table public.project_members (
  project_id uuid not null references public.projects (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  primary key (project_id, user_id)
);
create table public.invoices (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  amount numeric not null
);
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.projects enable row level security;
alter table public.project_members enable row level security;
alter table public.invoices enable row level security;
create policy "members: read own rows" on public.organization_members for select to authenticated using (user_id = auth.uid());
create policy "projects: members read" on public.projects for select to authenticated
  using (exists (select 1 from public.organization_members m where m.organization_id = projects.organization_id and m.user_id = auth.uid()));
`,
    "lib/supabase.ts": null,
  },
  pz3: {
    "app/api/join/route.ts": `import { NextResponse } from "next/server";
import { getUserFromRequest } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

// Joins the caller to the organization in the body. No invite is checked.
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const body = await req.json();
  await prisma.organization_members.upsert({
    where: { organization_id_user_id: { organization_id: body.organizationId, user_id: user.id } },
    create: { organization_id: body.organizationId, user_id: user.id, role: "member" },
    update: {},
  });
  return NextResponse.json({ ok: true });
}
`,
    "app/api/projects/route.ts": `import { NextResponse } from "next/server";
import { getUserFromRequest } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

// Projects of an organization the caller is a member of.
export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const member = await prisma.organization_members.findFirst({
    where: { organization_id: orgId, user_id: user.id },
  });
  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const rows = await prisma.projects.findMany({ where: { organization_id: orgId } });
  return NextResponse.json({ projects: rows });
}
`,
    "lib/auth.ts": `import { createClient } from "@supabase/supabase-js";

/** Resolves the caller from the bearer token through Supabase Auth. Identity only; authorization happens in the query. */
export async function getUserFromRequest(req: Request) {
  const auth = req.headers.get("authorization") ?? "";
  const token = auth.startsWith("Bearer ") ? auth.slice(7) : null;
  if (!token) return null;
  const sb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, {
    auth: { persistSession: false },
  });
  const { data, error } = await sb.auth.getUser(token);
  if (error || !data.user) return null;
  return data.user;
}
`,
    "lib/prisma.ts": `import { PrismaClient } from "@prisma/client";

/** One PrismaClient per process. Direct Postgres connection: Supabase RLS does not apply. */
const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };
export const prisma = globalForPrisma.prisma ?? new PrismaClient();
if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
`,
    "package.json": `{
  "name": "fixture-014-vulnerable",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev -p 3000",
    "build": "next build",
    "start": "next start -p 3000"
  },
  "dependencies": {
    "@supabase/ssr": "^0.7.0",
    "@supabase/supabase-js": "^2.57.0",
    "next": "^15.5.0",
    "react": "^19.1.0",
    "react-dom": "^19.1.0",
    "@prisma/client": "^6.0.0"
  },
  "devDependencies": {
    "@types/node": "^22.15.0",
    "@types/react": "^19.1.0",
    "typescript": "^5.8.0",
    "prisma": "^6.0.0"
  }
}
`,
    "prisma/schema.prisma": `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model organizations {
  id      String                 @id @default(uuid()) @db.Uuid
  name    String
  members organization_members[]
}

model organization_members {
  organization_id String        @db.Uuid
  user_id         String        @db.Uuid
  role            String        @default("member")
  organization    organizations @relation(fields: [organization_id], references: [id])

  @@id([organization_id, user_id])
}

model projects {
  id              String  @id @default(uuid()) @db.Uuid
  organization_id String  @db.Uuid
  owner_id        String? @db.Uuid
  shared          Boolean @default(false)
  name            String
}
`,
    "supabase/migrations/0001_init.sql": `create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null);
create table public.organization_members (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  primary key (organization_id, user_id)
);
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  owner_id uuid references auth.users (id),
  shared boolean not null default false,
  name text not null,
  created_at timestamptz not null default now()
);
create table public.project_members (
  project_id uuid not null references public.projects (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  primary key (project_id, user_id)
);
create table public.invoices (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  amount numeric not null
);
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.projects enable row level security;
alter table public.project_members enable row level security;
alter table public.invoices enable row level security;
create policy "members: read own rows" on public.organization_members for select to authenticated using (user_id = auth.uid());
create policy "projects: members read" on public.projects for select to authenticated
  using (exists (select 1 from public.organization_members m where m.organization_id = projects.organization_id and m.user_id = auth.uid()));
`,
    "lib/supabase.ts": null,
  },
  s2: {
    "app/api/join/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

// Joins the caller to the organization in the body. No invite is checked.
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const body = await req.json();
  const admin = createServiceRoleClient();
  const row: Record<string, string> = { user_id: user.id, role: "member" };
  row.organization_id = body.organizationId;
  const { error } = await admin.from("organization_members").upsert(row, { onConflict: "organization_id,user_id" });
  if (error) return NextResponse.json({ error: "Failed" }, { status: 500 });
  return NextResponse.json({ ok: true });
}
`,
  },
  j4: {
    "app/api/join/route.ts": `import { NextResponse } from "next/server";
import { getUserFromRequest } from "@/lib/supabase";
import { joinOrganization } from "@/lib/services/membership-service";

// Joins the caller to the organization in the body. No invite is checked.
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { organizationId } = await req.json();
  await joinOrganization(organizationId, user.id);
  return NextResponse.json({ ok: true });
}
`,
    "lib/repos/base-repo.ts": `import { createServiceRoleClient } from "@/lib/supabase";

export async function insertRow(organizationId: string, userId: string, role: string) {
  const admin = createServiceRoleClient();
  const { error } = await admin
    .from("organization_members")
    .insert({ organization_id: organizationId, user_id: userId, role });
  if (error) throw new Error(error.message);
}
`,
    "lib/repos/membership-repo.ts": `import { insertRow } from "@/lib/repos/base-repo";

export async function addMember(m: { organizationId: string; userId: string; role: string }) {
  return insertMemberRow(m.organizationId, m.userId, m.role);
}

async function insertMemberRow(organizationId: string, userId: string, role: string) {
  return insertRow(organizationId, userId, role);
}
`,
    "lib/services/membership-service.ts": `import { addMember } from "@/lib/repos/membership-repo";

export async function joinOrganization(organizationId: string, userId: string) {
  return addMember({ organizationId, userId, role: "member" });
}
`,
  },
  e1: {
    "supabase/functions/join-organization/index.ts": `import { createClient } from "npm:@supabase/supabase-js@2";

// Joins the caller to the organization in the body. No invite is checked.
Deno.serve(async (req) => {
  const authHeader = req.headers.get("Authorization") ?? "";
  const admin = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
  const { data: { user } } = await admin.auth.getUser(authHeader.replace("Bearer ", ""));
  if (!user) return new Response("Unauthorized", { status: 401 });
  const { organizationId } = await req.json();
  const { error } = await admin
    .from("organization_members")
    .insert({ organization_id: organizationId, user_id: user.id, role: "member" });
  if (error) return new Response("Failed", { status: 500 });
  return Response.json({ ok: true });
});
`,
  },
  um: {
    "app/auth/callback/route.ts": `import { NextResponse } from "next/server";
import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";
import { createServiceRoleClient } from "@/lib/supabase";

// After sign-up confirmation: add the user to the organization of their invite link.
export async function GET(req: Request) {
  const url = new URL(req.url);
  const code = url.searchParams.get("code");
  const store = await cookies();
  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, {
    cookies: { getAll: () => store.getAll(), setAll: (all) => all.forEach((c) => store.set(c.name, c.value, c.options)) },
  });
  if (code) await supabase.auth.exchangeCodeForSession(code);
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.redirect(new URL("/login", req.url));
  const organizationId = user.user_metadata.organization_id;
  if (organizationId) {
    const admin = createServiceRoleClient();
    await admin.from("organization_members").insert({ organization_id: organizationId, user_id: user.id });
  }
  return NextResponse.redirect(new URL("/dashboard", req.url));
}
`,
  },
  d1: {
    "supabase/migrations/0001_init.sql": `create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text unique);
create table public.organization_members (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  primary key (organization_id, user_id)
);
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  name text not null
);
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.projects enable row level security;
create policy "members: read own rows" on public.organization_members for select to authenticated using (user_id = auth.uid());

do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'organization_members' and policyname = 'members: join') then
    create policy "members: join" on public.organization_members for insert to authenticated
      with check (user_id = auth.uid());
  end if;
end
$$;
`,
  },
  d2: {
    "supabase/migrations/0001_init.sql": `create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text unique);
create table public.organization_members (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  primary key (organization_id, user_id)
);
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  name text not null
);
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.projects enable row level security;
create policy "members: read own rows" on public.organization_members for select to authenticated using (user_id = auth.uid());

create policy "members: add" on public.organization_members for insert to authenticated
  with check (exists (select 1 from public.organization_members m where m.organization_id = organization_members.organization_id and m.user_id = auth.uid()));
`,
    "supabase/migrations/0002_open_join.sql": `-- Open organizations: anyone may join.
alter policy "members: add" on public.organization_members with check (user_id = auth.uid());
`,
  },
  c: {
    "app/api/c1/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

// The projects are loaded by a hoisted helper before the membership check runs.
export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const admin = createServiceRoleClient();
  const early = loadProjects();
  const { data: member } = await admin
    .from("organization_members")
    .select("role")
    .eq("organization_id", orgId)
    .eq("user_id", user.id)
    .maybeSingle();
  if (!member) return NextResponse.json({ error: "Forbidden", projects: await early }, { status: 403 });
  return NextResponse.json({ projects: await early });

  async function loadProjects() {
    const { data } = await admin.from("projects").select("*").eq("organization_id", orgId);
    return data;
  }
}
`,
    "app/api/c2/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

// Acts for each listed member: the loop variable shadows the signed-in user.
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { orgId, members } = await req.json();
  const admin = createServiceRoleClient();
  const out: unknown[] = [];
  for (const user of members) {
    const { data: member } = await admin
      .from("organization_members")
      .select("role")
      .eq("organization_id", orgId)
      .eq("user_id", user.id)
      .maybeSingle();
    if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    const { data } = await admin.from("projects").select("*").eq("organization_id", orgId);
    out.push(data);
  }
  return NextResponse.json({ projects: out });
}
`,
    "app/api/c3/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

// Projects of every team member the caller lists, in the caller's organization.
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { orgId, team } = await req.json();
  const admin = createServiceRoleClient();
  const results = await Promise.all(
    team.map(async (user: { id: string }) => {
      const { data: member } = await admin
        .from("organization_members")
        .select("role")
        .eq("organization_id", orgId)
        .eq("user_id", user.id)
        .maybeSingle();
      if (!member) return null;
      const { data } = await admin.from("projects").select("*").eq("organization_id", orgId);
      return data;
    }),
  );
  return NextResponse.json({ projects: results });
}
`,
    "app/api/c4/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

// Projects owned by each listed teammate. The loop variable shadows the signed-in user.
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { orgId, teammates } = await req.json();
  const admin = createServiceRoleClient();
  const out: unknown[] = [];
  for (const user of teammates) {
    const { data } = await admin
      .from("projects")
      .select("*")
      .eq("organization_id", orgId)
      .eq("owner_id", user.id);
    out.push(data);
  }
  return NextResponse.json({ projects: out });
}
`,
    "app/api/m1/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

// Sections of the request are normalised after the check; one of them is the org.
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const body = await req.json();
  const admin = createServiceRoleClient();
  const { data: member } = await admin
    .from("organization_members")
    .select("role")
    .eq("organization_id", body.org.id)
    .eq("user_id", user.id)
    .maybeSingle();
  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  for (const section of Object.values(body)) {
    if (section && typeof section === "object" && body.defaults) Object.assign(section, body.defaults);
  }
  const { data } = await admin.from("projects").select("*").eq("organization_id", body.org.id);
  return NextResponse.json({ projects: data });
}
`,
    "app/api/m3/route.ts": `import { NextResponse } from "next/server";
import { createServiceRoleClient, getUserFromRequest } from "@/lib/supabase";

class TenantScope {
  org: { id: string };
  constructor(id: string) {
    this.org = { id };
  }
  switchTo(id: string) {
    this.org.id = id;
  }
}

// The tenant scope is switched after the membership check.
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const body = await req.json();
  const scope = new TenantScope(body.orgId);
  const admin = createServiceRoleClient();
  const { data: member } = await admin
    .from("organization_members")
    .select("role")
    .eq("organization_id", scope.org.id)
    .eq("user_id", user.id)
    .maybeSingle();
  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  if (body.compareWith) scope.switchTo(body.compareWith);
  const { data } = await admin.from("projects").select("*").eq("organization_id", scope.org.id);
  return NextResponse.json({ projects: data });
}
`,
    "supabase/migrations/0001_init.sql": `create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text unique);
create table public.organization_members (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  primary key (organization_id, user_id)
);
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  owner_id uuid references auth.users (id),
  name text not null
);
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.projects enable row level security;
create policy "members: read own rows" on public.organization_members for select to authenticated using (user_id = auth.uid());
`,
    "app/api/projects/route.ts": null,
  },
  ctrl0: {},
  pz0: {
    "app/api/projects/route.ts": `import { NextResponse } from "next/server";
import { getUserFromRequest } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

// Projects of an organization the caller is a member of.
export async function GET(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const orgId = new URL(req.url).searchParams.get("org");
  if (!orgId) return NextResponse.json({ error: "org is required" }, { status: 400 });
  const member = await prisma.organization_members.findFirst({
    where: { organization_id: orgId, user_id: user.id },
  });
  if (!member) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const rows = await prisma.projects.findMany({ where: { organization_id: orgId } });
  return NextResponse.json({ projects: rows });
}
`,
    "lib/auth.ts": `import { createClient } from "@supabase/supabase-js";

/** Resolves the caller from the bearer token through Supabase Auth. Identity only; authorization happens in the query. */
export async function getUserFromRequest(req: Request) {
  const auth = req.headers.get("authorization") ?? "";
  const token = auth.startsWith("Bearer ") ? auth.slice(7) : null;
  if (!token) return null;
  const sb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, {
    auth: { persistSession: false },
  });
  const { data, error } = await sb.auth.getUser(token);
  if (error || !data.user) return null;
  return data.user;
}
`,
    "lib/prisma.ts": `import { PrismaClient } from "@prisma/client";

/** One PrismaClient per process. Direct Postgres connection: Supabase RLS does not apply. */
const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };
export const prisma = globalForPrisma.prisma ?? new PrismaClient();
if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
`,
    "package.json": `{
  "name": "fixture-014-vulnerable",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev -p 3000",
    "build": "next build",
    "start": "next start -p 3000"
  },
  "dependencies": {
    "@supabase/ssr": "^0.7.0",
    "@supabase/supabase-js": "^2.57.0",
    "next": "^15.5.0",
    "react": "^19.1.0",
    "react-dom": "^19.1.0",
    "@prisma/client": "^6.0.0"
  },
  "devDependencies": {
    "@types/node": "^22.15.0",
    "@types/react": "^19.1.0",
    "typescript": "^5.8.0",
    "prisma": "^6.0.0"
  }
}
`,
    "prisma/schema.prisma": `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model organizations {
  id      String                 @id @default(uuid()) @db.Uuid
  name    String
  members organization_members[]
}

model organization_members {
  organization_id String        @db.Uuid
  user_id         String        @db.Uuid
  role            String        @default("member")
  organization    organizations @relation(fields: [organization_id], references: [id])

  @@id([organization_id, user_id])
}

model projects {
  id              String  @id @default(uuid()) @db.Uuid
  organization_id String  @db.Uuid
  owner_id        String? @db.Uuid
  shared          Boolean @default(false)
  name            String
}
`,
    "supabase/migrations/0001_init.sql": `create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null);
create table public.organization_members (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  primary key (organization_id, user_id)
);
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  owner_id uuid references auth.users (id),
  shared boolean not null default false,
  name text not null,
  created_at timestamptz not null default now()
);
create table public.project_members (
  project_id uuid not null references public.projects (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  primary key (project_id, user_id)
);
create table public.invoices (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  amount numeric not null
);
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.projects enable row level security;
alter table public.project_members enable row level security;
alter table public.invoices enable row level security;
create policy "members: read own rows" on public.organization_members for select to authenticated using (user_id = auth.uid());
create policy "projects: members read" on public.projects for select to authenticated
  using (exists (select 1 from public.organization_members m where m.organization_id = projects.organization_id and m.user_id = auth.uid()));
`,
    "lib/supabase.ts": null,
  },
  s3: {
    "app/orgs/actions.ts": `"use server";
import { createServiceRoleClient } from "@/lib/supabase";
import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";

export async function joinOrganization(organizationId: string) {
  const store = await cookies();
  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, {
    cookies: { getAll: () => store.getAll(), setAll: () => {} },
  });
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error("Unauthorized");
  const admin = createServiceRoleClient();
  await admin.from("organization_members").insert({ organization_id: organizationId, user_id: user.id });
}
`,
  },
  j2: {
    "app/api/join/route.ts": `import { NextResponse } from "next/server";
import { getUserFromRequest } from "@/lib/supabase";
import { joinOrganization } from "@/lib/services/membership-service";

// Joins the caller to the organization in the body. No invite is checked.
export async function POST(req: Request) {
  const user = await getUserFromRequest(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { organizationId } = await req.json();
  await joinOrganization(organizationId, user.id);
  return NextResponse.json({ ok: true });
}
`,
    "lib/services/membership-service.ts": `import { createServiceRoleClient } from "@/lib/supabase";

export async function joinOrganization(organizationId: string, userId: string) {
  const admin = createServiceRoleClient();
  const { error } = await admin
    .from("organization_members")
    .insert({ organization_id: organizationId, user_id: userId, role: "member" });
  if (error) throw new Error(error.message);
}
`,
  },
  d3: {
    "supabase/migrations/0001_init.sql": `create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text unique);
create table public.organization_members (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  primary key (organization_id, user_id)
);
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  name text not null
);
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.projects enable row level security;
create policy "members: read own rows" on public.organization_members for select to authenticated using (user_id = auth.uid());

do $$
begin
  execute $f$
    create or replace function public.join_organization(p_org uuid) returns void
    language plpgsql security definer set search_path = public as $b$
    begin
      insert into public.organization_members (organization_id, user_id) values (p_org, auth.uid());
    end;
    $b$;
  $f$;
end
$$;
`,
  },
  d4: {
    "supabase/migrations/0002_perf.sql": `-- The membership check in policies was slow; the app checks membership itself.
alter table public.organization_members disable row level security;
`,
  },
  d5: {
    "supabase/migrations/0001_init.sql": `create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text unique);
create table public.organization_members (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  primary key (organization_id, user_id)
);
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  name text not null
);
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.projects enable row level security;
create policy "members: read own rows" on public.organization_members for select to authenticated using (user_id = auth.uid());

create policy "members: manage own" on public.organization_members as permissive for all to authenticated
  using (user_id = (select auth.uid()));
`,
  },
};

interface Hit {
  file: string;
  line: number;
}

const scans = new Map<string, Hit[]>();

/** R4 findings of one counterexample project: the file and line of the query each points at. */
function r4(project: string): Hit[] {
  const cached = scans.get(project);
  if (cached) return cached;
  const dir = mkdtempSync(join(tmpdir(), `auditai-ownership-r3-${project}-`));
  const files: Record<string, string | null> = { ...BASE, ...R3[project] };
  for (const [rel, text] of Object.entries(files)) {
    if (text === null) continue;
    mkdirSync(dirname(join(dir, rel)), { recursive: true });
    writeFileSync(join(dir, rel), text);
  }
  const model = parseProject(dir);
  const hits = runRules([userControlledTenantScope], model, buildGraph(model), {
    now: "2026-09-23T00:00:00Z",
  })
    .map((f) => {
      const at = f.evidence[0]?.locations?.[1];
      return { file: at?.file ?? "", line: at?.line ?? 0 };
    })
    .sort((a, b) => a.file.localeCompare(b.file) || a.line - b.line);
  scans.set(project, hits);
  return hits;
}

/** The query lines R4 reports in one route file of a project. */
function lines(project: string, route: string): number[] {
  return r4(project)
    .filter((h) => h.file === `app/api/${route}/route.ts`)
    .map((h) => h.line);
}

describe("third review, A: a membership granted outside the policies the branch read", () => {
  it("t1: a SECURITY DEFINER trigger on auth.users copies organization_id from the sign-up metadata", () => {
    expect(lines("t1", "projects")).toEqual([11, 18]);
  });
  it("t2: a definer trigger on join_requests, which callers insert, copies the organization", () => {
    expect(lines("t2", "projects")).toEqual([11, 18]);
  });
  it("r1, r2: a join route calls a revoked membership function through the service role's rpc", () => {
    expect(lines("r1", "projects")).toEqual([11, 18]);
    expect(lines("r2", "projects")).toEqual([11, 18]);
  });
  it("pz1, pz2, pz3: Prisma connect, a nested create, and upsert's create join a requested organization", () => {
    expect(lines("pz1", "projects")).toEqual([11, 15]);
    expect(lines("pz2", "projects")).toEqual([11, 15]);
    expect(lines("pz3", "projects")).toEqual([11, 15]);
  });
  it("s2: a payload built piecewise takes organization_id from the body", () => {
    expect(lines("s2", "projects")).toEqual([11, 18]);
  });
  it("j4: the membership insert sits one call past the depth the parser follows", () => {
    expect(lines("j4", "projects")).toEqual([11, 18]);
  });
  it("e1: the membership insert lives in a Supabase Edge Function", () => {
    expect(lines("e1", "projects")).toEqual([11, 18]);
  });
  it("um: the auth callback joins the organization named in the user's own metadata", () => {
    expect(lines("um", "projects")).toEqual([11, 18]);
  });
  it("d1: a self-grant policy created inside a DO block", () => {
    expect(lines("d1", "projects")).toEqual([11, 18]);
  });
  it("d2: a strict insert policy opened later by ALTER POLICY", () => {
    expect(lines("d2", "projects")).toEqual([11, 18]);
  });
  it("twins ctrl0, pz0, s3, j2, d3, d4, d5: reported as main reports them", () => {
    for (const p of ["ctrl0", "s3", "j2", "d3", "d4", "d5"]) {
      expect(lines(p, "projects")).toEqual([11, 18]);
    }
    expect(lines("pz0", "projects")).toEqual([11, 15]);
  });
});

describe("third review, B and C: identity by name, and a tenant written through", () => {
  it("c4: a loop variable named user is not the caller", () => {
    expect(lines("c", "c4")).toEqual([12]);
  });
  it("c2, c3: a membership lookup keyed by a shadowing user in a loop or a callback", () => {
    expect(lines("c", "c2")).toEqual([12, 19]);
    expect(lines("c", "c3")).toEqual([12, 19]);
  });
  it("m1: Object.values hands out the nested tenant object, which Object.assign rewrites", () => {
    expect(lines("c", "m1")).toEqual([10, 20]);
  });
  it("twin c1: the hoisted-function variant, reported as main reports it", () => {
    expect(lines("c", "c1")).toEqual([12, 22]);
  });
});
